// Spanish translations for all 50 recipes
export interface RecipeTranslationES {
  titulo: string;
  descricao: string;
  rendimento: string;
  ingredientes: string[];
  preparo: string[];
  dicaBeatriz: string;
  beneficios: string[];
}

export const recipeTranslationsES: Record<string, RecipeTranslationES> = {
  "lentilhas-esau": {
    titulo: "Lentejas de Esaú con Cebolla Dorada",
    descricao:
      "Entonces Jacob dio a Esaú pan y un guisado de lentejas; y él comió, bebió, se levantó y se fue.",
    rendimento: "4 porciones",
    ingredientes: [
      "300 g de lentejas marrones secas",
      "2 cebollas medianas en rodajas finas",
      "4 dientes de ajo picados",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino en polvo",
      "1 cucharadita de pimentón dulce",
      "1 hoja de laurel",
      "1 cucharada de perejil fresco picado",
      "1 cucharada de cilantro fresco picado",
      "Sal y pimienta negra al gusto",
      "1 litro de agua",
    ],
    preparo: [
      "Lave las lentejas con agua corriente y reserve.",
      "Caliente 2 cucharadas de aceite a fuego medio. Sofría las cebollas lentamente por 15 minutos, revolviendo de vez en cuando, hasta que estén doradas.",
      "Añada el ajo y sofría 1 minuto más.",
      "Agregue el comino y el pimentón. Revuelva 30 segundos para liberar los aromas.",
      "Añada las lentejas, el agua y el laurel. Sazone con sal y pimienta.",
      "Cocine a fuego bajo, con la tapa a medio cerrar, por 25 a 30 minutos hasta que las lentejas estén blandas y el caldo espeso.",
      "Retire el laurel. Termine con el aceite restante, el perejil y el cilantro frescos.",
      "Sirva caliente, con pan de masa madre.",
    ],
    dicaBeatriz:
      "No se salte el tiempo de la cebolla. Es el secreto de este plato. La cebolla dorada lentamente es lo que transforma una sopa común en el guisado que hizo que un hermano cambiara su herencia.",
    beneficios: [
      "Rica en proteína vegetal",
      "Fuente de hierro y fibra",
      "Antiinflamatorio natural",
    ],
  },

  "peixe-galileia": {
    titulo: "Pescado de Galilea al Aceite y Romero",
    descricao: "Y tomándolos, los dio a sus discípulos para que los pusieran delante de ellos.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 filetes de pescado blanco (tilapia, corvina o róbalo) — 150 g cada uno",
      "4 cucharadas de aceite de oliva extra virgen",
      "3 dientes de ajo aplastados",
      "2 ramas de romero fresco",
      "1 limón (jugo y ralladura)",
      "1 cucharadita de sal gruesa",
      "Pimienta negra recién molida",
      "Hojas de albahaca fresca para terminar",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Sazone los filetes con sal, pimienta, jugo y ralladura de limón. Deje reposar 10 minutos.",
      "Extienda la mitad del aceite en una bandeja y acomode los filetes.",
      "Distribuya el ajo aplastado sobre los filetes y rocíe con el aceite restante.",
      "Coloque las ramas de romero sobre los filetes.",
      "Lleve al horno de 12 a 15 minutos, hasta que el pescado esté opaco y se deshaga fácilmente con un tenedor.",
      "Termine con hojas de albahaca fresca rasgadas con las manos.",
      "Sirva con arroz integral o pan de masa madre.",
    ],
    dicaBeatriz:
      "El pescado está listo cuando la carne se pone blanca y se separa en lascas. Un minuto más en el horno y se reseca. Confíe en sus ojos, no en el reloj.",
    beneficios: ["Rico en omega-3", "Antiinflamatorio", "Proteína magra de fácil digestión"],
  },

  "cevada-grao-de-bico": {
    titulo: "Cebada con Garbanzos y Comino",
    descricao:
      "Y le dijo Boaz a la hora de comer: Acércate, y come del pan, y moja tu bocado en el vinagre.",
    rendimento: "4 porciones",
    ingredientes: [
      "200 g de cebada en grano",
      "200 g de garbanzos secos (remojados 12 h la noche anterior)",
      "1 cebolla mediana picada",
      "3 dientes de ajo picados",
      "1 cucharada de comino en grano",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de cúrcuma",
      "1 cucharada de perejil fresco picado",
      "Sal y pimienta al gusto",
      "1,2 litros de agua o caldo de verduras",
    ],
    preparo: [
      "Escurra los garbanzos del remojo y reserve.",
      "Caliente el aceite a fuego medio. Tueste el comino en grano 30 segundos.",
      "Añada la cebolla y sofría 5 minutos. Agregue el ajo y sofría 1 minuto más.",
      "Incorpore la cebada y los garbanzos, revolviendo para envolver con el aceite.",
      "Sazone con sal, pimienta y cúrcuma.",
      "Añada el agua caliente y cocine a fuego bajo, tapa entreabierta, por unos 45 minutos hasta que todo esté blando.",
      "Agregue más agua caliente si es necesario durante la cocción.",
      "Termine con perejil fresco y un hilo generoso de aceite crudo.",
    ],
    dicaBeatriz:
      "La cebada y los garbanzos cocinan en tiempos distintos — por eso el secreto está en remojar los garbanzos toda la noche. Sin ese paso, quedan duros mientras la cebada se deshace.",
    beneficios: [
      "Energía estable y duradera",
      "Rico en fibras prebióticas",
      "Reduce los picos de glucemia",
    ],
  },

  "pao-sirio-legumes": {
    titulo: "Pan Árabe Relleno con Vegetales Asados",
    descricao: "No solo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 panes árabes integrales",
      "1 berenjena mediana en rodajas",
      "1 calabacín mediano en rodajas",
      "1 pimentón rojo en tiras",
      "1 cebolla morada en rodajas gruesas",
      "1 tomate maduro en rodajas",
      "4 cucharadas de aceite de oliva extra virgen",
      "2 cucharadas de hummus",
      "1 cucharadita de orégano",
      "1 cucharadita de tomillo seco",
      "Sal y pimienta al gusto",
      "Hojas de hierbabuena fresca",
    ],
    preparo: [
      "Precaliente el horno a 220 °C.",
      "Extienda los vegetales en una bandeja sin amontonar. Rocíe con 3 cucharadas de aceite, orégano, tomillo, sal y pimienta. Mezcle con las manos.",
      "Ase por 25 minutos, volteando a la mitad, hasta que estén dorados en los bordes.",
      "Caliente los panes árabes 1 minuto en una sartén seca.",
      "Abra cada pan y unte hummus en la parte interna.",
      "Rellene generosamente con los vegetales asados, tomate crudo y hojas de hierbabuena.",
      "Rocíe con el aceite restante y sirva de inmediato.",
    ],
    dicaBeatriz:
      "Los vegetales asados duran en la nevera hasta 3 días. Haga el doble el domingo y tenga el relleno listo para toda la semana. Es la comida más rápida que existe.",
    beneficios: [
      "Comida completa y equilibrada",
      "Fibras y vitaminas de los vegetales",
      "Sin ultraprocesados",
    ],
  },

  "tilapia-hortela": {
    titulo: "Tilapia a la Plancha con Salsa de Hierbabuena y Limón",
    descricao:
      "Y pan de la tierra en abundancia, y aceite, y dulzura, y todo lo que produce la abeja.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 filetes de tilapia — 150 g cada uno",
      "2 cucharadas de aceite de oliva extra virgen",
      "1 limón (jugo)",
      "Sal y pimienta al gusto",
      "— Para la salsa —",
      "4 cucharadas de yogur natural entero",
      "1 cucharada de aceite de oliva",
      "2 cucharadas de hierbabuena fresca picada",
      "1 diente de ajo aplastado",
      "1 limón (jugo y ralladura)",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Sazone los filetes con sal, pimienta y jugo de limón. Deje reposar 5 minutos.",
      "Mezcle todos los ingredientes de la salsa en un tazón. Reserve.",
      "Caliente una sartén antiadherente a fuego medio-alto. Añada el aceite.",
      "Coloque los filetes y cocine 3 minutos por cada lado sin mover.",
      "Transfiera los filetes a los platos.",
      "Sirva con una cucharada generosa de la salsa de hierbabuena encima.",
    ],
    dicaBeatriz:
      "No voltee el pescado antes de tiempo. La piel dorada solo se forma cuando lo deja quieto al menos 3 minutos. Paciencia, querida.",
    beneficios: [
      "Bajo en grasa saturada",
      "Probiótico natural (yogur)",
      "Antiinflamatorio (hierbabuena)",
    ],
  },

  mujadara: {
    titulo: "Mujadara — Arroz Integral con Lentejas",
    descricao:
      "El justo come para satisfacer su apetito, pero el estómago de los impíos sufre necesidad.",
    rendimento: "4 porciones",
    ingredientes: [
      "200 g de lentejas marrones",
      "200 g de arroz integral",
      "3 cebollas grandes en rodajas finas",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino en polvo",
      "1 cucharadita de canela en polvo",
      "1 hoja de laurel",
      "Sal y pimienta negra al gusto",
      "750 ml de agua",
      "Perejil fresco picado para terminar",
    ],
    preparo: [
      "Cocine las lentejas en 500 ml de agua con sal y laurel por 15 minutos. Escurra y guarde el caldo.",
      "Sofría el arroz integral en 1 cucharada de aceite por 1 minuto.",
      "Añada las lentejas, comino, canela, sal y pimienta. Revuelva.",
      "Agregue el caldo de lentejas más agua caliente hasta completar 600 ml de líquido.",
      "Cocine a fuego bajo, tapa cerrada, de 35 a 40 minutos.",
      "Mientras tanto, caramelice las cebollas con el aceite restante a fuego medio-bajo por 25 a 30 minutos.",
      "Sirva el arroz con lentejas cubierto por la cebolla caramelizada y perejil fresco.",
    ],
    dicaBeatriz:
      "La cebolla caramelizada es el corazón de este plato. No intente acelerarlo con fuego alto — se quemará y amargarà. Caramelizar toma tiempo, y el tiempo es parte del milagro.",
    beneficios: [
      "Proteína completa (arroz + lentejas)",
      "Saciedad prolongada",
      "Cero ultraprocesados",
    ],
  },

  "file-peixe-tomate": {
    titulo: "Filete de Pescado al Horno con Tomate y Albahaca",
    descricao:
      "El Señor es mi pastor, nada me faltará. En lugares de delicados pastos me hará descansar.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 filetes de pescado blanco firme (tilapia, corvina o merluza)",
      "4 tomates maduros sin piel en cubos",
      "1 cebolla mediana picada",
      "4 dientes de ajo en láminas",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 manojo de albahaca fresca",
      "1 cucharadita de orégano seco",
      "Sal y pimienta al gusto",
      "1 limón en rodajas",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Sofría la cebolla en 2 cucharadas de aceite por 5 minutos. Añada el ajo y sofría 1 minuto.",
      "Agregue los tomates, sal, pimienta y orégano. Cocine 8 minutos hasta formar una salsa rústica.",
      "Sazone los filetes con sal, pimienta y jugo de medio limón.",
      "Extienda la salsa de tomate en un refractario. Acomode los filetes encima.",
      "Coloque rodajas de limón sobre el pescado y rocíe con el aceite restante.",
      "Lleve al horno de 15 a 18 minutos.",
      "Retire y termine con albahaca fresca rasgada con las manos.",
    ],
    dicaBeatriz:
      "No corte la albahaca con el cuchillo. Ráguela con las manos, siempre. El cuchillo oxida las hojas y mata el aroma en segundos. Ese es uno de esos secretos que lo cambian todo sin costar nada.",
    beneficios: [
      "Licopeno del tomate antiinflamatorio",
      "Omega-3 del pescado blanco",
      "Antioxidante (albahaca)",
    ],
  },

  "grao-de-bico-crocante-pp": {
    titulo: "Garbanzos Asados con Pimentón y Hierbas",
    descricao:
      "Y pan y grano tostado y espigas verdes no comeréis hasta el mismo día en que traigáis la ofrenda a vuestro Dios.",
    rendimento: "4 porciones",
    ingredientes: [
      "400 g de garbanzos cocidos (bien escurridos y secos)",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de pimentón ahumado",
      "1 cucharadita de pimentón dulce",
      "1 cucharadita de comino en polvo",
      "1 cucharadita de orégano seco",
      "1 diente de ajo aplastado",
      "1 cucharadita de sal",
      "Pimienta negra al gusto",
      "Jugo de medio limón para terminar",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Seque muy bien los garbanzos con un paño limpio. Este paso es esencial para que queden crocantes.",
      "Mezcle los garbanzos con el aceite y todos los condimentos.",
      "Extienda en una bandeja con papel parafinado, en capa única sin amontonar.",
      "Hornee de 35 a 40 minutos, revolviendo cada 10 minutos, hasta que estén dorados.",
      "Retire del horno y rocíe con el jugo de limón.",
      "Sirva caliente como plato principal o a temperatura ambiente como snack.",
    ],
    dicaBeatriz:
      "La sequedad lo es todo aquí. Los garbanzos mojados nunca quedan crocantes — se cocinan en su propio vapor y quedan blandos. Use el paño. Confíe en mí.",
    beneficios: ["Proteína y fibra vegetal", "Snack sin grasas trans", "Energía estable"],
  },

  "frango-ervas": {
    titulo: "Pollo Asado con Hierbas del Campo y Aceite",
    descricao: "Como hace la gallina con sus polluelos debajo de las alas.",
    rendimento: "4–6 porciones",
    ingredientes: [
      "1 pollo entero — aprox. 1,5 kg",
      "5 cucharadas de aceite de oliva extra virgen",
      "6 dientes de ajo aplastados",
      "2 ramas grandes de romero fresco",
      "1 manojo de tomillo fresco",
      "2 limones",
      "1 cebolla grande en cuartos",
      "1 cucharada de sal gruesa",
      "Pimienta negra recién molida",
      "1 cucharadita de pimentón dulce",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Mezcle el aceite, ajo aplastado, jugo de 1 limón, sal, pimienta y pimentón en un tazón.",
      "Lave y seque el pollo con papel absorbente por dentro y por fuera.",
      "Unte la mezcla de aceite por todo el pollo, por dentro y bajo la piel de la pechuga.",
      "Rellene la cavidad con el 2.° limón en cuartos, la cebolla, el romero y el tomillo.",
      "Coloque en la bandeja con la pechuga hacia arriba.",
      "Hornee de 1 hora a 1 hora 15 minutos, rociando con los jugos cada 20 minutos.",
      "Deje reposar 10 minutos antes de cortar.",
    ],
    dicaBeatriz:
      "El reposo de 10 minutos después del horno no es opcional — es lo que mantiene el pollo jugoso. Si lo corta de inmediato, todos los jugos se escurren y la carne se reseca. Rece un padrenuestro mientras espera. Vale la pena.",
    beneficios: [
      "Proteína magra de alta calidad",
      "Hierbas con propiedades antimicrobianas",
      "Sin conservantes",
    ],
  },

  "quibe-assado": {
    titulo: "Quibe Asado de Trigo Integral con Hierbabuena",
    descricao:
      "Y él tomó mantequilla y leche, y el becerro que había preparado, y los puso delante de ellos.",
    rendimento: "6 porciones",
    ingredientes: [
      "300 g de trigo para quibe (fino)",
      "500 g de carne molida magra (res)",
      "1 cebolla grande rallada",
      "1 manojo de hierbabuena fresca picada",
      "1 cucharada de canela en polvo",
      "1 cucharadita de pimienta árabe",
      "4 cucharadas de aceite de oliva extra virgen",
      "Sal al gusto",
      "1 limón (jugo)",
      "Agua helada para hidratar el trigo",
    ],
    preparo: [
      "Cubra el trigo con agua helada y deje hidratar 30 minutos. Escurra y exprima bien con las manos.",
      "Precaliente el horno a 200 °C.",
      "Mezcle el trigo, carne molida, cebolla, hierbabuena, canela, pimienta árabe, sal y jugo de limón.",
      "Amase con las manos por 5 minutos hasta obtener una masa homogénea.",
      "Engrase una bandeja mediana con 1 cucharada de aceite. Extienda la masa uniformemente.",
      "Con un cuchillo, marque la superficie en rombos.",
      "Rocíe con el aceite restante y lleve al horno de 35 a 40 minutos hasta dorar.",
      "Sirva tibio o frío, con yogur natural al lado.",
    ],
    dicaBeatriz:
      "La diferencia entre un quibe seco y un quibe perfecto está en exprimir bien el trigo. Apriete con las manos hasta que casi no escurra agua. Ese es el secreto que toda mamá libanesa enseña a sus hijas — ahora usted también lo sabe.",
    beneficios: [
      "Trigo integral rico en fibra",
      "Hierbabuena con acción digestiva",
      "Hierro de la carne magra",
    ],
  },

  "lentilha-estufada": {
    titulo: "Lentejas Estofadas con Vegetales de Temporada",
    descricao: "Comerás la hierba del campo.",
    rendimento: "4 porciones",
    ingredientes: [
      "250 g de lentejas marrones",
      "2 zanahorias en rodajas",
      "1 calabacín en cubos",
      "1 batata dulce mediana en cubos",
      "1 cebolla grande picada",
      "3 dientes de ajo picados",
      "2 tomates maduros en cubos",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 hoja de laurel, comino y pimentón dulce al gusto",
      "Sal y pimienta al gusto",
      "1 cucharada de perejil fresco picado",
      "1 litro de agua o caldo de verduras",
    ],
    preparo: [
      "Sofría la cebolla en el aceite por 5 minutos. Añada el ajo.",
      "Agregue los tomates y cocine 5 minutos.",
      "Incorpore las lentejas, laurel, comino, pimentón, sal y pimienta. Mezcle.",
      "Añada la zanahoria, batata dulce y el agua. Cocine a fuego bajo por 25 minutos.",
      "Agregue el calabacín y cocine de 10 a 15 minutos más hasta que todo esté blando.",
      "Termine con aceite crudo y perejil fresco.",
      "Sirva solo o con arroz integral.",
    ],
    dicaBeatriz:
      "El calabacín entra de último porque se cocina más rápido. Si pone todo junto, queda aguado mientras la zanahoria aún está dura. Cada vegetal tiene su tiempo. Respételo.",
    beneficios: [
      "Vitaminas A y C de los vegetales",
      "Batata dulce antioxidante",
      "Receta sin gluten",
    ],
  },

  "salmao-endro": {
    titulo: "Salmón al Horno con Eneldo y Limón",
    descricao: "Diezmáis la menta, el eneldo y el comino.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 rodajas de salmón — 150 g cada una",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 manojo de eneldo fresco — 30 g",
      "2 limones",
      "3 dientes de ajo en láminas",
      "1 cucharadita de sal gruesa",
      "Pimienta negra recién molida",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Sazone el salmón con sal, pimienta y jugo de 1 limón. Deje reposar 10 minutos.",
      "Extienda 1 cucharada de aceite en la bandeja. Acomode el salmón.",
      "Cubra cada rodaja con ajo en láminas y ramas generosas de eneldo fresco.",
      "Coloque rodajas del 2.° limón sobre el salmón y rocíe con el aceite restante.",
      "Lleve al horno de 12 a 15 minutos hasta que la carne esté opaca por fuera pero aún rosada en el centro.",
      "Sirva con ensalada o arroz integral.",
    ],
    dicaBeatriz:
      "El salmón tiene un punto exacto — y llega antes de lo que imagina. Cuando al pincharlo con un tenedor la carne empieza a separarse en lascas pero aún parece húmeda en el centro, está listo.",
    beneficios: ["Mayor fuente de omega-3", "Antiinflamatorio celular", "Vitamina D y B12"],
  },

  "berinjela-recheada": {
    titulo: "Berenjena Rellena con Granos y Hierbas",
    descricao:
      "He aquí que os he dado toda planta que da semilla, que está sobre la faz de toda la tierra.",
    rendimento: "4 porciones",
    ingredientes: [
      "2 berenjenas grandes",
      "200 g de garbanzos cocidos",
      "100 g de quinoa cocida (o arroz integral)",
      "1 cebolla mediana picada",
      "3 dientes de ajo picados",
      "2 tomates maduros en cubos",
      "1 cucharada de hierbabuena fresca picada",
      "1 cucharada de perejil fresco picado",
      "1 cucharadita de comino, 1 de canela",
      "4 cucharadas de aceite de oliva extra virgen",
      "30 g de nueces picadas",
      "Sal, pimienta y jugo de 1 limón",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Corte las berenjenas a la mitad y retire la pulpa con una cuchara, dejando una cáscara de 1 cm. Pique la pulpa.",
      "Sazone las cáscaras con sal, rocíe con aceite y hornee 15 minutos.",
      "Sofría la cebolla en el aceite. Añada el ajo y la pulpa picada. Sofría 5 minutos.",
      "Agregue los tomates, garbanzos, quinoa, comino, canela, sal y pimienta. Cocine 5 minutos.",
      "Retire del fuego. Mezcle las hierbas frescas, las nueces y el jugo de limón.",
      "Rellene las cáscaras, rocíe con aceite y vuelva al horno por 15 minutos.",
      "Sirva tibio.",
    ],
    dicaBeatriz:
      "No tire la pulpa. Es el corazón del relleno. Cada berenjena tiene dentro de sí lo que necesita para convertirse en plato completo — solo necesita ser organizado de nuevo.",
    beneficios: ["Proteína completa vegetal", "Antioxidante (berenjena)", "Omega-3 de las nueces"],
  },

  // SALADS
  "salada-profeta": {
    titulo: "Ensalada del Profeta — Hojas, Granada y Nueces",
    descricao: "Tierra de trigo y cebada, de vides, higueras y granados.",
    rendimento: "4 porciones",
    ingredientes: [
      "200 g de hojas verdes variadas (rúcula, lechuga romana, espinaca baby)",
      "1 granada grande (semillas)",
      "50 g de nueces en trozos",
      "1 cebolla morada pequeña en rodajas finas",
      "50 g de queso blanco fresco desmenuzado (opcional)",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharada de vinagre de manzana",
      "1 cucharadita de miel",
      "Sal y pimienta negra al gusto",
    ],
    preparo: [
      "Lave y seque bien las hojas. Coloque en una fuente amplia.",
      "Distribuya la cebolla morada en rodajas finas sobre las hojas.",
      "Esparza las semillas de granada por toda la ensalada.",
      "Polvoree las nueces en trozos y el queso blanco desmenuzado.",
      "Mezcle el aceite, vinagre, miel, sal y pimienta. Bata con un tenedor hasta emulsionar.",
      "Rocíe la ensalada con el aderezo al momento de servir.",
      "Sirva de inmediato.",
    ],
    dicaBeatriz:
      "Para sacar las semillas de la granada sin ensuciar, córtela a la mitad y golpee la espalda con una cuchara de madera, sosteniendo sobre un tazón. Las semillas caen solas.",
    beneficios: [
      "Polifenoles de la granada anticancerígenos",
      "Omega-3 de las nueces",
      "Vitaminas K y A de las hojas",
    ],
  },

  "homus-tradicional": {
    titulo: "Hummus Tradicional al Aceite",
    descricao: "Pan de la tierra en abundancia, y aceite, y dulzura.",
    rendimento: "6 porciones",
    ingredientes: [
      "400 g de garbanzos cocidos (con el caldo reservado)",
      "3 cucharadas de tahini (pasta de ajonjolí)",
      "1 limón grande (jugo)",
      "2 dientes de ajo",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino en polvo",
      "Sal al gusto",
      "Pimentón dulce y perejil fresco para terminar",
    ],
    preparo: [
      "En la licuadora, ponga los garbanzos, el tahini, el jugo de limón, el ajo, el comino y la sal.",
      "Licúe 1 minuto, añadiendo el caldo de garbanzos poco a poco (aprox. 4 cucharadas) hasta obtener una pasta cremosa.",
      "Añada 2 cucharadas de aceite y licúe 30 segundos más.",
      "Pruebe y ajuste la sal y el limón.",
      "Transfiera a un plato hondo. Con la espalda de una cuchara, haga espirales en la superficie.",
      "Rocíe generosamente con el aceite restante.",
      "Polvoree pimentón y perejil fresco encima.",
      "Sirva con pan árabe integral o vegetales crudos en palitos.",
    ],
    dicaBeatriz:
      "El caldo de cocción del garbanzo es el secreto de la cremosidad. Nunca lo tire. Si usa garbanzo de lata, reemplácelo con el líquido de la lata (llamado aquafaba). Hace la diferencia.",
    beneficios: [
      "Proteína y fibra del garbanzo",
      "Calcio y hierro del tahini",
      "Grasa buena del aceite",
    ],
  },

  babaganuche: {
    titulo: "Babaganoush — Pasta de Berenjena Asada",
    descricao: "Comerás la hierba del campo.",
    rendimento: "4 porciones",
    ingredientes: [
      "2 berenjenas grandes",
      "3 cucharadas de tahini",
      "1 limón grande (jugo)",
      "2 dientes de ajo aplastados",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino en polvo",
      "Sal al gusto",
      "Perejil picado y ajonjolí tostado para terminar",
    ],
    preparo: [
      "Precaliente el horno a 220 °C.",
      "Pinche las berenjenas con un tenedor. Lleve al horno por 40 minutos volteando a la mitad.",
      "Retire y deje enfriar. Corte a la mitad y saque la pulpa con una cuchara.",
      "Coloque la pulpa en un colador fino por 5 minutos para escurrir el exceso de líquido.",
      "Aplaste la pulpa con un tenedor (no use procesador — la textura rústica es parte de la identidad del plato).",
      "Mezcle el tahini, el limón, el ajo, el comino, 2 cucharadas de aceite y sal.",
      "Transfiera a un plato, rocíe con el aceite restante, perejil y ajonjolí tostado.",
    ],
    dicaBeatriz:
      "Si tiene estufa de gas, puede quemar la berenjena directamente en la llama antes de ir al horno. El sabor ahumado queda mil veces más intenso. Es como lo hacía mi abuela.",
    beneficios: [
      "Fibras y antioxidantes de la berenjena",
      "Calcio del ajonjolí",
      "Antiinflamatorio",
    ],
  },

  tabule: {
    titulo: "Tabulé de Trigo, Hierbabuena y Tomate",
    descricao: "He aquí que os he dado toda planta que da semilla.",
    rendimento: "4 porciones",
    ingredientes: [
      "150 g de trigo fino para tabulé",
      "4 tomates maduros y firmes en cubos pequeños",
      "1 manojo grande de perejil fresco — 80 g",
      "1 manojo mediano de hierbabuena fresca — 30 g",
      "1 cebolla morada pequeña en cubos bien pequeños",
      "1 pepino mediano en cubos pequeños",
      "5 cucharadas de aceite de oliva extra virgen",
      "2 limones (jugo)",
      "Sal y pimienta negra al gusto",
    ],
    preparo: [
      "Cubra el trigo con agua helada y deje hidratar 20 minutos. Escurra y exprima con las manos.",
      "Pique el perejil y la hierbabuena muy finamente.",
      "En un tazón grande, mezcle el trigo escurrido, los tomates, el pepino, la cebolla morada, el perejil y la hierbabuena picados.",
      "Sazone con el jugo de limón, el aceite, sal y pimienta.",
      "Mezcle delicadamente con las manos o con dos tenedores.",
      "Deje reposar 15 minutos en la nevera antes de servir.",
      "Sirva como acompañamiento o en hojas de lechuga, como pequeños envoltorios.",
    ],
    dicaBeatriz:
      "El tabulé de verdad tiene más hierba que trigo. Si mira su plato y ve más trigo que verde, volvió a hacer ensalada de trigo — no tabulé. Coraje con las hierbas. El verde es el protagonista.",
    beneficios: [
      "Vitamina C y hierro del perejil",
      "Digestivo (hierbabuena)",
      "Fibras del trigo integral",
    ],
  },

  "pepino-iogurte": {
    titulo: "Ensalada de Pepino con Yogur y Hierbabuena",
    descricao: "Nos acordamos de los pepinos que comíamos en Egipto de balde.",
    rendimento: "4 porciones",
    ingredientes: [
      "2 pepinos medianos en cubos pequeños",
      "300 g de yogur natural entero (sin azúcar)",
      "1 cucharada de hierbabuena fresca picada",
      "1 diente de ajo aplastado",
      "2 cucharadas de aceite de oliva extra virgen",
      "Sal al gusto",
      "Pimienta negra recién molida",
      "Hojas extra de hierbabuena para terminar",
    ],
    preparo: [
      "Corte el pepino, polvoree sal y deje escurrir por 10 minutos en un colador.",
      "Mezcle el yogur, el ajo, la hierbabuena, el aceite, sal y pimienta.",
      "Añada los cubos de pepino escurridos.",
      "Mezcle delicadamente y transfiera a una fuente.",
      "Termine con hojas frescas de hierbabuena y un hilo de aceite.",
      "Sirva fría.",
    ],
    dicaBeatriz:
      "Esta es la compañía perfecta para platos calientes y especiados. El yogur y el pepino refrescan el paladar y el estómago. Sírvala junto al quibe, las lentejas estofadas o el pollo asado.",
    beneficios: [
      "Probiótico natural (yogur)",
      "Hidratante (pepino 96% agua)",
      "Digestivo (hierbabuena)",
    ],
  },

  "cenoura-mel": {
    titulo: "Zanahorias Asadas con Miel y Comino",
    descricao: "Come miel, hijo mío, porque es buena.",
    rendimento: "4 porciones",
    ingredientes: [
      "600 g de zanahorias medianas",
      "3 cucharadas de aceite de oliva extra virgen",
      "2 cucharadas de miel",
      "1 cucharadita de comino en polvo",
      "1 cucharadita de pimentón dulce",
      "Sal y pimienta al gusto",
      "1 cucharada de perejil fresco",
      "Semillas de ajonjolí para terminar",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Si son pequeñas, deje las zanahorias enteras; si son grandes, corte a lo largo por la mitad.",
      "Mezcle el aceite, la miel, el comino, el pimentón, sal y pimienta.",
      "Cubra las zanahorias con la mezcla.",
      "Extienda en una bandeja con papel parafinado sin amontonar.",
      "Hornee de 30 a 35 minutos, volteando a la mitad, hasta que estén blandas y caramelizadas.",
      "Termine con perejil y semillas de ajonjolí.",
    ],
    dicaBeatriz:
      "La zanahoria es una de las pocas raíces que se vuelven dulces en el horno sin azúcar. La miel solo intensifica ese dulce natural. Sírvala junto a carne, pescado o pollo — y prepárese: el plato vuelve vacío.",
    beneficios: [
      "Beta-caroteno (pro-vitamina A)",
      "Miel antimicrobiana natural",
      "Fibras para el tránsito intestinal",
    ],
  },

  "beterraba-endro": {
    titulo: "Remolacha al Aceite y Eneldo",
    descricao: "Diezmáis la menta, el eneldo y el comino.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 remolachas medianas",
      "4 cucharadas de aceite de oliva extra virgen",
      "2 cucharadas de vinagre de manzana",
      "1 manojo pequeño de eneldo fresco — 20 g",
      "1 diente de ajo aplastado",
      "1 cucharadita de miel",
      "Sal y pimienta al gusto",
      "50 g de nueces (opcional)",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Envuelva cada remolacha en papel aluminio y lleve al horno por 50 minutos.",
      "Retire, deje enfriar y pele con las manos (la cáscara sale fácilmente).",
      "Corte en cubos o rodajas gruesas.",
      "Mezcle el aceite, el vinagre, el ajo, la miel, sal y pimienta.",
      "Cubra la remolacha con el aderezo junto con el eneldo picado.",
      "Transfiera a una fuente y termine con nueces.",
      "Sirva tibia o a temperatura ambiente.",
    ],
    dicaBeatriz:
      "La remolacha asada con cáscara preserva todo el sabor dulce y la textura aterciopelada. Cocida en agua, queda aguada y pierde lo mejor. Vale la hora de horno.",
    beneficios: [
      "Nitratos para la presión y energía",
      "Betalaínas antioxidantes",
      "Hierro y ácido fólico",
    ],
  },

  "lentilha-morna": {
    titulo: "Ensalada Tibia de Lentejas con Cebolla Morada",
    descricao: "El justo come para satisfacer su apetito.",
    rendimento: "4 porciones",
    ingredientes: [
      "250 g de lentejas marrones",
      "1 cebolla morada en rodajas finas",
      "1 pimentón amarillo en cubos",
      "1 tomate maduro firme en cubos",
      "1 manojo pequeño de perejil fresco",
      "4 cucharadas de aceite de oliva extra virgen",
      "2 cucharadas de vinagre de manzana",
      "1 cucharadita de mostaza dijon",
      "1 hoja de laurel",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Cocine las lentejas con agua y laurel de 20 a 25 minutos hasta que estén blandas (no papilla). Sale los últimos 5 minutos.",
      "Escurra, descarte el laurel y transfiera a un tazón grande.",
      "Aún tibias, añada la cebolla morada, el pimentón y el tomate.",
      "Mezcle el aceite, el vinagre, la mostaza, sal y pimienta. Bata con un tenedor.",
      "Vierta el aderezo sobre las lentejas tibias.",
      "Añada el perejil y mezcle delicadamente.",
      "Sirva tibia o a temperatura ambiente.",
    ],
    dicaBeatriz:
      "La lenteja tibia absorbe el aderezo de una manera que la lenteja fría no absorbe. Por eso el condimento entra mientras aún está caliente. Pequeño detalle, gran diferencia.",
    beneficios: [
      "Proteína vegetal de alta absorción",
      "Hierro no heme + vitamina C",
      "Antiinflamatorio",
    ],
  },

  "grao-crocante-salada": {
    titulo: "Garbanzos Crocantes con Pimentón",
    descricao: "Comió Boaz, y bebió, y se alegró su corazón.",
    rendimento: "4 porciones",
    ingredientes: [
      "400 g de garbanzos cocidos (bien escurridos)",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de pimentón ahumado",
      "1 cucharadita de pimentón dulce",
      "1 cucharadita de ajo en polvo",
      "1 cucharadita de comino en polvo",
      "Sal al gusto",
      "Pimienta negra recién molida",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Escurra los garbanzos, extiéndalos en un paño limpio y séquelos completamente, removiendo las cáscaras sueltas.",
      "Mezcle el aceite y todos los condimentos.",
      "Cubra los garbanzos con la mezcla.",
      "Extienda en una bandeja con papel parafinado, en capa única.",
      "Hornee de 40 a 45 minutos, revolviendo cada 10 minutos.",
      "Deje enfriar 5 minutos sobre la bandeja — quedan aún más crocantes al enfriarse.",
      "Sirva como snack o polvoree sobre ensaladas.",
    ],
    dicaBeatriz:
      "La diferencia entre crocante y blando es el paño de cocina. Esos 5 minutos de trabajo son lo que separa un snack memorable de una decepción.",
    beneficios: ["Proteína y fibra", "Snack sin grasas trans", "Energía estable"],
  },

  "salada-figos": {
    titulo: "Ensalada de Higos Frescos, Queso y Nueces",
    descricao: "Cada uno se sentará debajo de su vid y debajo de su higuera.",
    rendimento: "4 porciones",
    ingredientes: [
      "6 higos maduros y firmes",
      "150 g de queso blanco fresco (ricota o queso de cabra)",
      "100 g de rúcula",
      "50 g de nueces en trozos",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharada de miel",
      "1 cucharada de vinagre balsámico (opcional)",
      "Sal y pimienta al gusto",
      "Hojas de hierbabuena fresca",
    ],
    preparo: [
      "Corte cada higo en 4 partes.",
      "Coloque la rúcula en una fuente amplia.",
      "Distribuya los higos cortados sobre las hojas.",
      "Desmenuce el queso con las manos y esparza por la ensalada.",
      "Polvoree las nueces.",
      "Mezcle el aceite, la miel, el vinagre, sal y pimienta. Rocíe la ensalada.",
      "Termine con hojas de hierbabuena fresca.",
    ],
    dicaBeatriz:
      "El higo fresco tiene temporada corta. Cuando esté en época, haga esta ensalada el máximo que pueda — es la más bonita del libro. Fuera de temporada, use higos secos hidratados en agua tibia por 10 minutos.",
    beneficios: ["Potasio y fibra del higo", "Antioxidantes de la rúcula", "Omega-3 de las nueces"],
  },

  // SOUPS
  "caldo-daniel": {
    titulo: "Caldo de Daniel — Lentejas, Zanahoria y Hierbas",
    descricao:
      "Te ruego que pruebes a tus siervos por diez días, y nos den legumbres a comer y agua a beber.",
    rendimento: "4 porciones",
    ingredientes: [
      "250 g de lentejas marrones",
      "2 zanahorias medianas en cubos",
      "1 cebolla grande picada",
      "3 dientes de ajo picados",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 hoja de laurel",
      "1 cucharadita de comino en polvo",
      "1 cucharadita de cúrcuma",
      "1 cucharada de perejil y cilantro frescos picados",
      "1,2 litros de agua o caldo de verduras",
      "Sal y pimienta al gusto",
      "1 limón en cuartos para servir",
    ],
    preparo: [
      "Lave bien las lentejas y reserve.",
      "Caliente 2 cucharadas de aceite. Sofría la cebolla por 5 minutos.",
      "Añada el ajo y sofría 2 minutos.",
      "Agregue el comino y la cúrcuma. Revuelva 30 segundos.",
      "Incorpore las lentejas, las zanahorias, el laurel y el agua caliente. Sazone.",
      "Cocine a fuego bajo por 30 minutos.",
      "Para versión cremosa, licúe la mitad y devuelva a la olla.",
      "Termine con el aceite restante y las hierbas frescas.",
      "Sirva caliente con un cuarto de limón al lado.",
    ],
    dicaBeatriz:
      "El limón al servir no es decoración — es parte esencial del plato. El jugo cítrico activa el hierro de las lentejas para que el cuerpo lo absorba mejor. Pequeño gesto, gran diferencia nutricional.",
    beneficios: [
      "Cúrcuma poderoso antiinflamatorio",
      "Hierro + vitamina C (máxima absorción)",
      "Fibras solubles",
    ],
  },

  "sopa-cevada": {
    titulo: "Sopa de Cebada con Champiñones",
    descricao: "El reino de los cielos es semejante al grano de mostaza.",
    rendimento: "4 porciones",
    ingredientes: [
      "200 g de cebada en grano",
      "300 g de champiñones frescos en láminas",
      "1 cebolla grande picada",
      "3 dientes de ajo picados",
      "2 zanahorias en cubos",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 hoja de laurel",
      "2 ramas de tomillo fresco",
      "1,5 litros de agua o caldo de verduras",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Lave la cebada y reserve.",
      "Sofría la cebolla en el aceite por 5 minutos. Añada el ajo.",
      "Agregue los champiñones. Sofría por 8 minutos hasta que se doren ligeramente.",
      "Incorpore la cebada, las zanahorias, el laurel, el tomillo y el agua caliente.",
      "Sazone y cocine a fuego bajo de 50 minutos a 1 hora hasta que la cebada esté blanda.",
      "Añada más agua caliente si es necesario.",
      "Retire el laurel y el tomillo. Termine con aceite y perejil.",
      "Sirva bien caliente.",
    ],
    dicaBeatriz:
      "No tenga prisa con los champiñones. Sofríalos hasta que se doren — ahí está todo el sabor de la sopa. El champiñón sofrito a las carreras queda aguado, y sopa aguada de champiñón es tristeza en el plato.",
    beneficios: [
      "Beta-glucanos de la cebada (inmunidad)",
      "Champiñones ricos en vitamina D",
      "Prebiótico natural",
    ],
  },

  "creme-abobora": {
    titulo: "Crema de Ahuyama con Jengibre",
    descricao:
      "Todo lo que tiene vida y se mueve será para vuestro sustento; como las plantas verdes, os lo he dado todo.",
    rendimento: "4 porciones",
    ingredientes: [
      "800 g de ahuyama (calabaza) pelada en cubos",
      "1 cebolla grande picada",
      "3 dientes de ajo picados",
      "1 trozo de jengibre fresco de 3 cm, picado",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de cúrcuma",
      "1 cucharadita de comino en polvo",
      "1 litro de agua o caldo de verduras",
      "100 ml de leche de coco (opcional)",
      "Sal y pimienta al gusto",
      "Semillas de ahuyama tostadas y cilantro para terminar",
    ],
    preparo: [
      "Sofría la cebolla en el aceite por 5 minutos. Añada el ajo y el jengibre.",
      "Agregue la cúrcuma y el comino. Revuelva 30 segundos.",
      "Incorpore la ahuyama en cubos. Sofría 5 minutos.",
      "Añada el agua caliente. Cocine a fuego bajo de 25 a 30 minutos.",
      "Licúe hasta obtener una crema lisa.",
      "Vuelva a la olla. Añada la leche de coco si lo desea y caliente 2 minutos.",
      "Sirva con aceite, semillas tostadas y cilantro.",
    ],
    dicaBeatriz:
      "El jengibre es el ingrediente que saca esta sopa de lo común. No lo omita ni reduzca la cantidad — es responsable del calor que calienta por dentro y tiene poderosas propiedades antiinflamatorias.",
    beneficios: [
      "Jengibre antiinflamatorio y digestivo",
      "Beta-caroteno de la ahuyama",
      "Cúrcuma detox",
    ],
  },

  "sopa-grao": {
    titulo: "Sopa de Garbanzos con Espinaca",
    descricao: "El Señor está cerca de los que tienen el corazón contrito.",
    rendimento: "4 porciones",
    ingredientes: [
      "400 g de garbanzos cocidos",
      "300 g de espinaca fresca",
      "1 cebolla grande picada",
      "4 dientes de ajo picados",
      "2 tomates maduros sin piel en cubos",
      "4 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino y pimentón ahumado",
      "1 limón (jugo)",
      "1 litro de agua caliente",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Sofría la cebolla en el aceite. Añada el ajo.",
      "Agregue el comino y el pimentón. Revuelva 30 segundos.",
      "Incorpore los tomates y cocine 5 minutos.",
      "Añada los garbanzos y el agua caliente. Cocine 15 minutos.",
      "Para espesar, licúe 1 cucharón y devuelva a la olla.",
      "Añada la espinaca fresca y cocine solo 3 minutos.",
      "Termine con el jugo de limón, el aceite restante y el perejil.",
    ],
    dicaBeatriz:
      "La espinaca entra de último, siempre. La espinaca que se cocina demasiado pierde color, hierro y queda con ese sabor a comida vieja. Tres minutos de olla es todo lo que necesita para marchitarse perfectamente.",
    beneficios: [
      "Hierro de la espinaca + vitamina C (doble absorción)",
      "Proteína completa",
      "Luteína para la visión",
    ],
  },

  "caldo-verde": {
    titulo: "Caldo Verde de Col, Papa y Aceite",
    descricao: "Dios dijo: He aquí que os he dado toda planta que da semilla.",
    rendimento: "4 porciones",
    ingredientes: [
      "600 g de papas en cubos",
      "1 manojo grande de col rizada (kale)",
      "1 cebolla grande picada",
      "4 dientes de ajo picados",
      "5 cucharadas de aceite de oliva extra virgen",
      "1,2 litros de agua",
      "Sal y pimienta al gusto",
      "Ají seco al gusto (opcional)",
    ],
    preparo: [
      "Sofría la cebolla en 2 cucharadas de aceite. Añada el ajo.",
      "Añada las papas en cubos. Sofría 3 minutos.",
      "Añada el agua caliente, sal y pimienta. Cocine 20 minutos hasta que las papas estén blandas.",
      "Corte la col en tiras muy finas (chifonada).",
      "Licúe la sopa hasta obtener una crema lisa. Vuelva a la olla.",
      "Añada la col y cocine solo de 2 a 3 minutos.",
      "Termine con el aceite restante y el ají seco.",
      "Sirva de inmediato, bien caliente.",
    ],
    dicaBeatriz:
      "La col cortada muy fina es lo que hace el caldo verde de verdad. La col gruesa se cocina demasiado y pierde la vivacidad. Cuanto más fino el corte, más bonita y sabrosa queda la sopa.",
    beneficios: [
      "Col superalimento (vit. K, C, hierro)",
      "Papa fuente de energía",
      "Aceite antiinflamatorio",
    ],
  },

  "sopa-tomate": {
    titulo: "Sopa de Tomate Asado con Albahaca",
    descricao: "Gustad y ved que el Señor es bueno.",
    rendimento: "4 porciones",
    ingredientes: [
      "1 kg de tomates maduros (italianos o perita)",
      "1 cebolla grande en cuartos",
      "6 dientes de ajo con cáscara",
      "5 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de orégano seco",
      "1 manojo de albahaca fresca",
      "1 cucharada de miel",
      "800 ml de agua caliente",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Corte los tomates a la mitad. Extienda en una bandeja con la cebolla y el ajo. Rocíe con aceite, orégano, sal y pimienta.",
      "Hornee de 35 a 40 minutos hasta que los tomates estén marchitos y dorados.",
      "Exprima los dientes de ajo para sacar la pulpa blanda. Deseche las cáscaras.",
      "Licúe todo con la mitad de la albahaca.",
      "Transfiera a una olla. Añada el agua caliente y la miel. Ajuste la sal.",
      "Caliente 5 minutos sin que hierva fuerte.",
      "Sirva con aceite, albahaca fresca rasgada y pimienta recién molida.",
    ],
    dicaBeatriz:
      "El pequeño gesto de la miel es lo que hace esta sopa parecer profesional. El tomate tiene acidez natural — cuando la equilibra con un toque de dulce, el sabor completo queda redondo.",
    beneficios: [
      "Licopeno potenciado por el calor del horno",
      "Miel antimicrobiana",
      "Albahaca adaptógena",
    ],
  },

  "sopa-feijao-branco": {
    titulo: "Sopa de Frijoles Blancos con Romero",
    descricao: "Y te saciará el alma.",
    rendimento: "4 porciones",
    ingredientes: [
      "300 g de frijoles blancos secos (remojados 12 h)",
      "1 cebolla grande picada",
      "4 dientes de ajo picados",
      "2 zanahorias en cubos pequeños",
      "4 cucharadas de aceite de oliva extra virgen",
      "2 ramas de romero fresco",
      "1 hoja de laurel",
      "1,5 litros de agua caliente",
      "Sal, pimienta y limón para terminar",
    ],
    preparo: [
      "Escurra los frijoles del remojo.",
      "Sofría la cebolla en el aceite. Añada el ajo y las zanahorias.",
      "Incorpore los frijoles, el romero, el laurel y el agua caliente.",
      "Cocine a fuego bajo de 35 a 45 minutos. Añada la sal solo en los últimos 10 minutos.",
      "Retire el laurel y el romero.",
      "Licúe 1 o 2 cucharones y devuelva (el resto queda con el frijol entero).",
      "Sirva con aceite, perejil y gotas de limón.",
    ],
    dicaBeatriz:
      "La sal en el frijol es como hablar con prisa: demasiado pronto lo arruina, en el momento justo lo transforma. Siempre en los últimos 10 minutos — ese secreto vale para todos los frijoles de este libro.",
    beneficios: [
      "Fibras solubles para el colesterol",
      "Proteína vegetal completa",
      "Romero antioxidante y digestivo",
    ],
  },

  // HERBS
  "azeite-aromatizado": {
    titulo: "Aceite Aromatizado con Romero y Ajo",
    descricao: "El buen nombre es mejor que el precioso ungüento.",
    rendimento: "500 ml",
    ingredientes: [
      "500 ml de aceite de oliva extra virgen",
      "4 ramas grandes de romero fresco",
      "6 dientes de ajo ligeramente aplastados (sin cortar)",
      "1 cucharadita de pimienta negra en grano",
      "1 hoja de laurel",
    ],
    preparo: [
      "Lave y seque muy bien el romero. Cualquier gota de agua puede arruinar el aceite.",
      "Aplaste ligeramente los dientes de ajo con la hoja del cuchillo, sin cortarlos.",
      "Caliente el aceite a fuego muy bajo por 3 minutos (no debe freír). Solo tibiar.",
      "Retire del fuego y deje enfriar 5 minutos.",
      "Coloque el romero, el ajo, la pimienta en grano y el laurel en una botella de vidrio esterilizada.",
      "Vierta el aceite tibio encima, cubriendo completamente todos los ingredientes.",
      "Tape y deje reposar en lugar fresco y oscuro por 7 días.",
      "Consérvese en la nevera hasta 1 mes.",
    ],
    dicaBeatriz:
      "Coloque una etiqueta con la fecha de producción en la botella. El aceite aromatizado casero debe consumirse en 30 días — después, las hierbas en inmersión pueden desarrollar bacterias.",
    beneficios: [
      "Polifenoles del aceite antiinflamatorios",
      "Alicina del ajo antibacteriana",
      "Romero antioxidante",
    ],
  },

  "molho-hortela": {
    titulo: "Salsa de Hierbabuena y Yogur",
    descricao: "Diezmáis la menta, el eneldo y el comino.",
    rendimento: "300 g",
    ingredientes: [
      "300 g de yogur natural entero (sin azúcar)",
      "1 manojo pequeño de hierbabuena fresca — 20 g",
      "2 dientes de ajo aplastados",
      "2 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de jugo de limón",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Lave la hierbabuena. Séquela y retire solo las hojas.",
      "Pique finamente con un cuchillo afilado (no use procesador — oxida y amarga la hierbabuena).",
      "Mezcle el yogur, el ajo, la hierbabuena, el aceite, el limón, sal y pimienta.",
      "Cubra y lleve a la nevera al menos 30 minutos.",
      "Consérvese en recipiente cerrado en la nevera hasta 3 días.",
    ],
    dicaBeatriz:
      "Siempre aplaste el ajo con el costado del cuchillo antes de añadir al yogur. El ajo en cubos crea puntos amargos. Aplastado, se distribuye en sabor, no en mordida.",
    beneficios: ["Probiótico natural", "Hierbabuena digestiva y refrescante", "Calcio del yogur"],
  },

  "pesto-biblico": {
    titulo: "Pesto Bíblico de Albahaca con Nueces",
    descricao: "El justo florecerá como la palmera.",
    rendimento: "200 g",
    ingredientes: [
      "80 g de hojas de albahaca fresca",
      "50 g de nueces",
      "3 dientes de ajo",
      "1 limón (jugo y ralladura)",
      "150 ml de aceite de oliva extra virgen",
      "Sal gruesa al gusto",
      "Pimienta negra recién molida",
    ],
    preparo: [
      "Lave la albahaca y séquela muy bien. Retire solo las hojas.",
      "Tueste las nueces en sartén seca a fuego bajo por 3 minutos. Deje enfriar.",
      "En el procesador, triture groseramente el ajo, las nueces y una pizca de sal gruesa.",
      "Añada las hojas de albahaca y la ralladura de limón. Pulse para incorporar.",
      "Con el aparato encendido, vierta el aceite en hilo hasta obtener una pasta cremosa.",
      "Sazone con jugo de limón, sal y pimienta.",
      "Transfiera a un vidrio esterilizado y cubra la superficie con un hilo de aceite.",
      "Consérvese en la nevera hasta 7 días.",
    ],
    dicaBeatriz:
      "El secreto del color verde vivo es no procesar demasiado. Cuanto más tiempo en el procesador, más oscuro y amargo queda. Triture en pulsos cortos. El pesto debe tener color brillante y textura ligeramente rústica.",
    beneficios: [
      "Omega-3 de las nueces",
      "Albahaca con vitamina K y magnesio",
      "Antioxidante poderoso",
    ],
  },

  "tahine-caseiro": {
    titulo: "Tahini Puro Casero",
    descricao: "Comerás a la mesa del rey continuamente.",
    rendimento: "250 g",
    ingredientes: [
      "300 g de semillas de ajonjolí blanco",
      "3 a 5 cucharadas de aceite de oliva extra virgen (o aceite neutro)",
      "Pizca de sal (opcional)",
    ],
    preparo: [
      "Precaliente el horno a 150 °C.",
      "Extienda las semillas de ajonjolí en una bandeja en capa única.",
      "Tueste de 10 a 12 minutos, revolviendo a la mitad, hasta que estén ligeramente doradas. Esté atento: el ajonjolí se quema rápido.",
      "Retire y deje enfriar completamente (15 minutos).",
      "Triture en un procesador potente por 2 minutos. Raspe los lados y continúe 2 minutos más.",
      "Empiece a añadir el aceite, 1 cucharada a la vez, procesando entre cada adición hasta obtener una pasta lisa y cremosa.",
      "Añada sal al gusto si lo desea.",
      "Transfiera a un vidrio esterilizado. Consérvese en la nevera hasta 2 meses. Revuelva antes de usar.",
    ],
    dicaBeatriz:
      "Tostar el ajonjolí antes de procesar es lo que separa el tahini casero del industrial. Las semillas crudas dan una pasta amarga y sin alma. Tostadas, se convierten en esa pasta dorada, rica y perfumada que hace cualquier plato especial.",
    beneficios: ["Calcio (muy rico)", "Grasas monoinsaturadas", "Proteína completa vegetal"],
  },

  "molho-tahine": {
    titulo: "Salsa de Tahini con Limón y Ajo",
    descricao: "Pan de la tierra en abundancia, y aceite, y dulzura.",
    rendimento: "200 ml",
    ingredientes: [
      "4 cucharadas de tahini",
      "1 limón grande (jugo)",
      "2 dientes de ajo aplastados",
      "2 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de comino en polvo",
      "1 cucharada de perejil fresco picado",
      "Sal al gusto",
      "Agua helada para ajustar la textura",
    ],
    preparo: [
      "Ponga el tahini, el jugo de limón y el ajo aplastado en un tazón.",
      "Revuelva con un tenedor — al principio la mezcla se pondrá dura y grumosa (esto es normal).",
      "Continúe revolviendo, añadiendo agua helada 1 cucharada a la vez.",
      "Después de unas 4 a 6 cucharadas de agua, la textura se transforma en crema lisa, brillante y color marfil.",
      "Añada el aceite, el comino, la sal y el perejil picado. Mezcle.",
      "Pruebe y ajuste el limón y la sal.",
      "Consérvese en recipiente cerrado en la nevera hasta 5 días.",
    ],
    dicaBeatriz:
      "El agua debe estar helada. Es el choque entre el agua fría y la pasta de tahini lo que crea la emulsión cremosa típica de la salsa árabe. El agua a temperatura ambiente no tiene el mismo efecto.",
    beneficios: ["Calcio y hierro del tahini", "Vitamina C del limón", "Digestivo (comino)"],
  },

  "vinagrete-ervas": {
    titulo: "Vinagreta de Hierbas del Campo",
    descricao:
      "Bendito el hombre que confía en el Señor, porque será como árbol plantado junto a las aguas.",
    rendimento: "250 ml",
    ingredientes: [
      "40 g de perejil fresco",
      "30 g de cilantro fresco",
      "20 g de hierbabuena fresca",
      "2 dientes de ajo aplastados",
      "1 limón grande (jugo y ralladura)",
      "2 cucharadas de vinagre de manzana",
      "150 ml de aceite de oliva extra virgen",
      "1 cucharadita de miel",
      "Sal y pimienta al gusto",
    ],
    preparo: [
      "Lave y seque todas las hierbas. Retire las hojas.",
      "Pique todas las hierbas finamente con un cuchillo afilado.",
      "Mezcle el ajo, el jugo de limón, la ralladura, el vinagre, la miel, sal y pimienta. Bata con tenedor.",
      "Añada el aceite en hilo, batiendo continuamente hasta emulsionar.",
      "Por último, incorpore las hierbas picadas.",
      "Transfiera a un vidrio con tapa.",
      "Consérvese en la nevera hasta 7 días. Revuelva antes de usar.",
    ],
    dicaBeatriz:
      "Sirva esta vinagreta en pequeñas jarras de vidrio en la mesa para que cada persona se sirva sola. La vinagreta vertida sobre la ensalada en la cocina la marchita en minutos. En la mesa, al momento, mantiene todo fresco y crocante.",
    beneficios: [
      "Vitamina C y hierro del perejil",
      "Digestivo (cilantro y hierbabuena)",
      "Antioxidante de las hierbas",
    ],
  },

  "sal-aromatizado": {
    titulo: "Sal Aromatizada con Hierbas de las Escrituras",
    descricao:
      "Vosotros sois la sal de la tierra; si la sal se vuelve insípida, ¿con qué se sazonará?",
    rendimento: "200 g",
    ingredientes: [
      "200 g de sal gruesa (preferiblemente sal marina)",
      "2 cucharadas de orégano seco",
      "2 cucharadas de romero seco",
      "1 cucharada de tomillo seco",
      "1 cucharada de albahaca seca",
      "1 cucharada de pimentón dulce",
      "1 cucharadita de pimienta negra molida",
      "1 cucharadita de comino en polvo",
      "2 dientes de ajo fresco aplastados",
      "Ralladura de 1 limón",
    ],
    preparo: [
      "Coloque la sal en un tazón grande.",
      "Añada todas las hierbas secas, el pimentón, la pimienta, el comino, el ajo y la ralladura de limón.",
      "Frote con las manos por 2 minutos para liberar los aceites esenciales.",
      "Extienda en una bandeja con papel parafinado.",
      "Deje reposar en lugar seco y aireado por 24 horas.",
      "Transfiera a un frasco de vidrio con tapa hermética.",
      "Use menos que la sal común — esta sazona mucho más.",
      "Consérvese hasta 6 meses.",
    ],
    dicaBeatriz:
      "Prepare un frasco para su casa y dos para regalar. La sal aromatizada casera en frasquito bonito con etiqueta escrita a mano es uno de los regalos más bonitos que existen. Cuesta poco, vale oro.",
    beneficios: [
      "Sin aditivos químicos",
      "Hierbas con propiedades medicinales",
      "Reduce el uso de sal refinada",
    ],
  },

  // DESSERTS
  "figos-mel": {
    titulo: "Higos con Miel y Nueces al Horno",
    descricao: "Levántate, amada mía, hermosa mía, y ven. La higuera ha echado sus higos.",
    rendimento: "4 porciones",
    ingredientes: [
      "8 higos maduros y firmes",
      "4 cucharadas de miel pura",
      "50 g de nueces en trozos",
      "1 cucharadita de canela en polvo",
      "Ralladura de 1 limón",
      "1 cucharada de aceite de oliva extra virgen",
      "4 cucharadas de yogur natural entero (opcional)",
    ],
    preparo: [
      "Precaliente el horno a 200 °C.",
      "Lave los higos y corte en cruz en la parte superior, creando una flor abierta.",
      "Coloque en una bandeja pequeña con la abertura hacia arriba.",
      "Ponga un poco de miel dentro de cada higo (aprox. 1 cucharadita por unidad).",
      "Distribuya las nueces en trozos sobre los higos.",
      "Polvoree canela y ralladura de limón.",
      "Rocíe con el aceite y lleve al horno por 12 minutos.",
      "Sirva tibio, con yogur natural al lado.",
    ],
    dicaBeatriz:
      "Los higos maduros son frágiles — manéjelos con cuidado. Y el yogur al lado equilibra perfectamente el dulce de la miel. No es decoración — es parte del plato.",
    beneficios: ["Potasio y fibra del higo", "Miel antimicrobiana", "Omega-3 de las nueces"],
  },

  "maca-assada": {
    titulo: "Manzana Asada con Canela y Miel",
    descricao: "El Señor te bendecirá en todas las obras de tus manos.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 manzanas rojas medianas (gala o fuji)",
      "4 cucharadas de miel",
      "1 cucharada de canela en polvo",
      "1 cucharadita de clavo de olor en polvo",
      "40 g de nueces en trozos",
      "40 g de pasas",
      "2 cucharadas de mantequilla sin sal (o aceite)",
      "Jugo de medio limón",
      "100 ml de agua",
    ],
    preparo: [
      "Precaliente el horno a 180 °C.",
      "Retire el centro de cada manzana cuidadosamente, manteniendo la base intacta.",
      "Mezcle las nueces, las pasas, 2 cucharadas de miel, la canela y el clavo.",
      "Rellene cada manzana con la mezcla.",
      "Coloque mantequilla sobre cada manzana rellena.",
      "Acomode en una bandeja, rocíe el resto de la miel y añada el agua al fondo.",
      "Lleve al horno de 30 a 35 minutos, rociando 2 veces.",
      "Sirva tibia con el almíbar de la bandeja encima.",
    ],
    dicaBeatriz:
      "El almíbar que se forma en el fondo de la bandeja es la mitad del plato. No lo tire. Sirva cada manzana con una cucharada generosa encima.",
    beneficios: [
      "Pectina de la manzana (colesterol)",
      "Canela estabiliza la glucemia",
      "Hierro de las pasas",
    ],
  },

  "tamara-recheada": {
    titulo: "Dátiles Rellenos con Pasta de Almendra",
    descricao: "Comed lo que es bueno, y que vuestra alma se deleite.",
    rendimento: "12 unidades",
    ingredientes: [
      "12 dátiles grandes (preferiblemente medjool)",
      "6 cucharadas de pasta de almendra (o mantequilla de maní sin azúcar)",
      "12 almendras enteras",
      "2 cucharadas de coco rallado sin azúcar",
      "1 cucharadita de canela en polvo",
      "1 cucharada de miel",
      "Pizca de sal de mar en escamas (opcional)",
    ],
    preparo: [
      "Haga un corte longitudinal en cada dátil y retire el hueso.",
      "Mezcle la pasta de almendra, la miel y la canela.",
      "Con una cucharita pequeña, rellene cada dátil con la mezcla.",
      "Coloque una almendra sobre el relleno de cada dátil, presionando ligeramente.",
      "Acomode en una fuente bonita.",
      "Polvoree coco rallado por encima de todos.",
      "Termine con una pizca muy pequeña de sal de mar en escamas si lo desea.",
      "Sirva a temperatura ambiente con té de hierbabuena o café.",
    ],
    dicaBeatriz:
      "Los dátiles medjool son grandes, suculentos y brillantes. Son más caros que los comunes, pero valen cada centavo para esta receta. Si no los encuentra, remoje los comunes en agua tibia por 10 minutos.",
    beneficios: [
      "Energía natural sin azúcar refinada",
      "Magnesio y potasio de los dátiles",
      "Vitamina E de las almendras",
    ],
  },

  "iogurte-mel": {
    titulo: "Postre de Yogur con Miel y Granola",
    descricao: "Una tierra que mana leche y miel.",
    rendimento: "4 porciones",
    ingredientes: [
      "— Para la granola casera (rinde 400 g) —",
      "200 g de avena en copos gruesos",
      "50 g de nueces en trozos",
      "50 g de almendras en láminas",
      "30 g de semillas de girasol",
      "4 cucharadas de miel",
      "3 cucharadas de aceite de oliva",
      "1 cucharadita de canela y pizca de sal",
      "— Para servir (cada porción) —",
      "200 g de yogur natural entero (sin azúcar)",
      "2 cucharadas de granola casera",
      "1 cucharadita de miel",
      "Fruta fresca de temporada",
    ],
    preparo: [
      "Precaliente el horno a 160 °C.",
      "Mezcle la avena, las nueces, las almendras, las semillas, la canela y la sal.",
      "Mezcle la miel y el aceite tibio. Vierta sobre la avena y revuelva bien.",
      "Extienda en una bandeja con papel parafinado en capa delgada.",
      "Hornee de 25 a 30 minutos, revolviendo cada 8 minutos.",
      "Deje enfriar completamente sobre la bandeja (queda crocante al enfriarse).",
      "Para servir: capas de yogur, granola, miel y fruta en un vaso bonito.",
    ],
    dicaBeatriz:
      "Prepare la granola el domingo por la mañana. Una bandeja alcanza para toda la semana. Y recuerde: dobla su crocancia después de enfriarse. Déjela quieta antes de probar.",
    beneficios: [
      "Probiótico del yogur",
      "Beta-glucano de la avena para el colesterol",
      "Miel con enzimas digestivas",
    ],
  },

  "creme-tamaras": {
    titulo: "Crema de Dátiles — Sin Azúcar, Sin Leche",
    descricao: "La dulzura habitará en tu corazón.",
    rendimento: "4 porciones",
    ingredientes: [
      "300 g de dátiles sin hueso (medjool o hidratados)",
      "200 ml de agua caliente",
      "100 g de anacardos crudos (remojados 2 h)",
      "1 cucharada de cacao en polvo 100% (opcional)",
      "1 cucharadita de extracto de vainilla",
      "Pizca de sal",
      "Coco rallado y frutos rojos frescos para terminar",
    ],
    preparo: [
      "Remoje los dátiles en agua caliente por 10 minutos. Escurra, reservando 100 ml del agua.",
      "Escurra también los anacardos.",
      "En la licuadora, ponga los dátiles, los anacardos, el agua reservada, el cacao, la vainilla y la sal.",
      "Licúe a velocidad alta de 3 a 5 minutos, parando para raspar los lados, hasta obtener una crema absolutamente lisa.",
      "Si la textura queda muy espesa, añada agua, 1 cucharada a la vez.",
      "Transfiera a 4 ramekins individuales.",
      "Cubra con film plástico en contacto con la superficie y lleve a la nevera al menos 4 horas.",
      "Al servir, termine con coco rallado y frutos rojos frescos.",
    ],
    dicaBeatriz:
      "El anacardo remojado es lo que da la textura sedosa. El anacardo seco queda granuloso. Y en la nevera toda la noche, la textura queda aún más firme y el sabor más profundo.",
    beneficios: [
      "Endulzado solo con dátiles naturales",
      "Calcio y magnesio del anacardo",
      "Fibras solubles",
    ],
  },

  "pera-vinho": {
    titulo: "Pera al Vino Suave con Clavo y Canela",
    descricao: "Como la higuera que da sus primeros higos.",
    rendimento: "4 porciones",
    ingredientes: [
      "4 peras firmes con tallo (williams o portuguesa)",
      "700 ml de jugo de uva integral (sin azúcar) O 500 ml de vino tinto seco + 200 ml de agua",
      "3 cucharadas de miel",
      "2 palitos de canela",
      "4 clavos de olor",
      "1 anís estrellado (opcional)",
      "Ralladura de 1 naranja y jugo de medio limón",
    ],
    preparo: [
      "Pele las peras manteniendo el tallo. Corte una finita tajada de la base para que queden paradas.",
      "En una olla alta, mezcle el jugo, la miel, la canela, el clavo, el anís, la ralladura de naranja y el jugo de limón.",
      "Caliente hasta hervir. Reduzca a fuego bajo.",
      "Coloque las peras paradas en la olla y cocine tapado de 25 a 35 minutos, volteando cada 10 minutos.",
      "Retire las peras con cuidado y reserve.",
      "Aumente el fuego de la olla y cocine el caldo de 10 a 15 minutos hasta que se reduzca formando un almíbar brillante.",
      "Sirva cada pera en un platito hondo con el almíbar generoso encima.",
    ],
    dicaBeatriz:
      "Este postre queda aún más bonito servido en platos blancos, para que el color vinado de la pera se destaque. Las peras se van tiñendo del color del líquido mientras se cocinan — cuanto más tiempo volteadas, más uniformes quedan.",
    beneficios: [
      "Polifenoles de la uva antioxidantes",
      "Canela estabiliza la glucemia",
      "Fibra de la pera para la digestión",
    ],
  },

  "bolo-mel": {
    titulo: "Torta de Miel y Nueces Sin Azúcar",
    descricao: "Y será suave tu dulzura.",
    rendimento: "10 porciones",
    ingredientes: [
      "300 g de harina de trigo integral",
      "200 ml de miel pura",
      "3 huevos",
      "100 ml de aceite de oliva (o aceite neutro)",
      "100 ml de leche",
      "100 g de nueces picadas",
      "1 cucharada de canela en polvo",
      "1 cucharadita de clavo de olor en polvo",
      "1 cucharadita de bicarbonato de sodio",
      "1 cucharadita de polvo de hornear",
      "Pizca de sal y ralladura de 1 naranja",
    ],
    preparo: [
      "Precaliente el horno a 170 °C. Engrase un molde de torta inglesa.",
      "Bata la miel, los huevos y el aceite hasta obtener mezcla homogénea.",
      "Añada la leche y la ralladura de naranja.",
      "Mezcle por separado la harina, la canela, el clavo, el bicarbonato, el polvo de hornear y la sal.",
      "Una los secos a los líquidos, revolviendo hasta incorporar (no bata en exceso).",
      "Añada las nueces picadas con una espátula.",
      "Vierta en el molde y hornee de 40 a 45 minutos.",
      "Deje enfriar 15 minutos antes de desmoldar.",
    ],
    dicaBeatriz:
      "Esta torta queda mejor al día siguiente. La miel se asienta, la canela se intensifica. Hágala de noche, deje reposar, y sírvala en el desayuno del día siguiente. Descubrirá lo que le estoy diciendo.",
    beneficios: [
      "Miel rica en enzimas y antioxidantes",
      "Nueces omega-3 y vitamina E",
      "Harina integral con fibras",
    ],
  },

  "roma-iogurte": {
    titulo: "Granada con Yogur y Hierbabuena",
    descricao: "Allí te daré mi amor, donde han florecido los granados.",
    rendimento: "4 porciones",
    ingredientes: [
      "400 g de yogur natural entero (sin azúcar)",
      "1 granada grande (semillas)",
      "4 cucharaditas de miel",
      "1 cucharada de hierbabuena fresca picada",
      "4 cucharaditas de pistacho sin sal (opcional)",
    ],
    preparo: [
      "Corte la granada a la mitad y saque las semillas golpeando la espalda con una cuchara de madera.",
      "Divida el yogur entre 4 tazas individuales.",
      "Distribuya las semillas de granada generosamente sobre cada porción.",
      "Rocíe con miel y polvoree hierbabuena fresca picada.",
      "Termine con pistacho ligeramente picado si lo usa.",
      "Sirva de inmediato, bien fría.",
    ],
    dicaBeatriz:
      "Este postre pide yogur de buena calidad. El yogur aguado arruina el plato. Busque el más cremoso posible — es el ingrediente principal disfrazado de secundario.",
    beneficios: [
      "Polifenoles de la granada anticancerígenos",
      "Probiótico del yogur",
      "Pistacho rico en proteína",
    ],
  },

  // ANCHOR RECIPES
  "pao-discipulos": {
    titulo: "Pan de los Discípulos — Masa Madre Tradicional",
    descricao:
      "Y tomando los cinco panes y los dos peces, y mirando al cielo, los bendijo, y los partió.",
    rendimento: "1 pan grande (10 rebanadas)",
    ingredientes: [
      "100 g de masa madre activa (alimentada en las últimas 4 a 8 horas)",
      "350 ml de agua filtrada tibia (30 °C)",
      "400 g de harina de trigo blanca",
      "100 g de harina de trigo integral",
      "10 g de sal fina",
    ],
    preparo: [
      "Mezcle la masa madre con el agua tibia. Revuelva para disolver.",
      "Añada las harinas. Mezcle con cuchara hasta obtener una masa rústica. Cubra y deje reposar 30 minutos (autólisis).",
      "Añada la sal y amase por 5 minutos, estirando y doblando dentro del tazón.",
      "En las primeras 2 horas de fermentación, cada 30 min haga un pliegue (estire un lado y dóblelo sobre la masa). Repita por 2 horas.",
      "Fermente a temperatura ambiente de 4 a 6 horas hasta que doble el volumen.",
      "Forme una bola y lleve a la nevera de 12 a 18 horas en un tazón forrado con paño enharinado.",
      "Precaliente el horno a 230 °C con una olla de hierro tapada dentro por 30 min.",
      "Vuelque la masa en la olla. Haga un corte de 1 cm en la parte superior. Hornee tapado 25 min, luego destapado de 15 a 20 min.",
      "Deje enfriar 1 hora antes de cortar.",
    ],
    dicaBeatriz:
      "Sé que parece mucho trabajo. Pero lo que hace con sus manos no es solo un pan — es el gesto más ancestral de la humanidad. Hágalo una vez, compártalo con su familia con una oración antes — y entenderá por qué vale cada minuto.",
    beneficios: [
      "Fermentación natural prebiótica",
      "Reduce el índice glucémico del pan",
      "Sin aditivos industriales",
    ],
  },

  "pao-azimo": {
    titulo: "Pan Ácimo — Pan Sin Levadura de la Pascua",
    descricao:
      "Y cocieron la masa que trajeron de Egipto, haciendo tortas sin levadura, porque no había leudado.",
    rendimento: "6 panes",
    ingredientes: [
      "300 g de harina de trigo integral",
      "150 ml de agua tibia",
      "3 cucharadas de aceite de oliva extra virgen",
      "1 cucharadita de sal",
    ],
    preparo: [
      "Precaliente el horno a 220 °C con una bandeja vacía dentro.",
      "Mezcle la harina y la sal. Añada el agua tibia y el aceite.",
      "Mezcle y amase por 5 minutos hasta obtener una masa lisa. Deje reposar 10 min.",
      "Divida en 6 porciones iguales y estire cada una con rodillo hasta obtener un disco fino de 20 cm.",
      "Pinche cada disco varias veces con un tenedor.",
      "Coloque en la bandeja caliente y hornee de 3 a 5 minutos por cada lado, volteando una vez.",
      "Sirva caliente con hummus, babaganoush, queso blanco o aceite y sal.",
    ],
    dicaBeatriz:
      "Prepare este pan el día de la Pascua con su familia. Antes de servir, abra la Biblia en Éxodo 12 y lea el pasaje. No es solo una comida — es una transmisión de fe.",
    beneficios: [
      "Sin levadura (digestión más ligera)",
      "Harina integral con fibras",
      "Aceite antiinflamatorio",
    ],
  },

  "cordeiro-pascal": {
    titulo: "Cordero Pascual Asado con Hierbas Amargas",
    descricao:
      "Y aquella noche comerán la carne asada al fuego, con panes sin levadura; con hierbas amargas lo comerán.",
    rendimento: "6–8 porciones",
    ingredientes: [
      "1,5 kg de paleta o pernil de cordero",
      "6 dientes de ajo aplastados",
      "3 ramas de romero fresco",
      "3 ramas de tomillo fresco",
      "1 manojo de hierbabuena fresca",
      "100 ml de aceite de oliva extra virgen",
      "2 limones (jugo y ralladura)",
      "1 cucharada de sal gruesa y pimienta molida",
      "1 cucharada de comino en polvo",
      "200 ml de agua o caldo de carne",
      "Rúcula o berros frescos para servir (hierbas amargas)",
    ],
    preparo: [
      "Retire el cordero de la nevera 1 hora antes de cocinar.",
      "Precaliente el horno a 160 °C.",
      "Aplaste el ajo, sal, pimienta, comino, jugo y ralladura de limón. Añada la mitad del aceite — pasta lista.",
      "Unte la pasta por todo el cordero, bajo los pliegues.",
      "Extienda el romero, el tomillo y la hierbabuena en la bandeja. Coloque el cordero encima.",
      "Rocíe con el aceite restante y añada el agua al fondo.",
      "Cubra con papel aluminio bien sellado. Hornee 2 horas 30 minutos.",
      "Retire el aluminio. Aumente a 200 °C y hornee 25 min más.",
      "Deje reposar 15 min. Sirva con rúcula al lado.",
    ],
    dicaBeatriz:
      "Las hierbas amargas al lado no son decoración — representan la amargura del cautiverio en Egipto. Cuando sirve cordero con rúcula cruda al lado, repite un gesto de más de tres mil años. Cuente esa historia en la mesa.",
    beneficios: [
      "Proteína completa de alta calidad",
      "Hierro hemo de alta absorción",
      "Zinc para la inmunidad",
    ],
  },

  "suco-sagrado": {
    titulo: "Jugo Sagrado de la Mañana — Naranja, Jengibre y Hierbabuena",
    descricao: "Tus labios son como el panal que destila.",
    rendimento: "1 porción",
    ingredientes: [
      "2 naranjas maduras (jugo fresco — aprox. 200 ml)",
      "1 trozo de jengibre fresco — aprox. 2 cm",
      "8 a 10 hojas de hierbabuena fresca",
      "100 ml de agua helada",
      "1 cucharadita de miel (opcional)",
      "Cubos de hielo al gusto",
    ],
    preparo: [
      "Exprima las naranjas y reserve el jugo.",
      "Pele el jengibre y córtelo en rodajas finas.",
      "Lave las hojas de hierbabuena.",
      "En la licuadora, ponga el jugo de naranja, el jengibre, la hierbabuena y el agua helada.",
      "Licúe de 30 segundos a 1 minuto.",
      "Cuele en un colador fino para retirar las fibras (opcional).",
      "Añada la miel si lo desea y mezcle.",
      "Sirva de inmediato en vaso alto, con hielo y algunas hojitas extra de hierbabuena.",
      "Beba despacio, en ayunas, antes del desayuno.",
    ],
    dicaBeatriz:
      "Prepare este jugo todos los días durante los primeros 21 días. En 1 semana notará el rostro menos hinchado. En 2, la barriga más liviana. En 3, una energía que no tenía en años. Es el gesto más simple que puede hacer ahora por el templo de su cuerpo.",
    beneficios: [
      "Vitamina C (2× la necesidad diaria)",
      "Jengibre antiinflamatorio y termogénico",
      "Hierbabuena digestiva y detox",
    ],
  },

  "vinho-uvas": {
    titulo: "Vino Suave de Uvas — Bebida Fermentada Sin Alcohol",
    descricao:
      "Tomando el cáliz, y habiendo dado gracias, se los dio, diciendo: Bebed de él todos.",
    rendimento: "1 litro (6–8 porciones)",
    ingredientes: [
      "1 litro de jugo de uva integral 100% (sin azúcar añadida)",
      "4 clavos de olor",
      "1 palito de canela",
      "4 granos de cardamomo ligeramente abiertos (opcional)",
      "Ralladura de media naranja y medio limón",
      "2 cucharadas de miel (opcional)",
      "1 cucharada de pasas oscuras",
    ],
    preparo: [
      "Caliente el jugo a fuego bajo sin que hierva por 5 minutos.",
      "Añada el clavo, la canela, el cardamomo, la ralladura de naranja y limón.",
      "Apague el fuego. Cubra y deje en infusión por 30 minutos.",
      "Cuele con un colador fino. Añada la miel y disuelva.",
      "Transfiera a una botella de vidrio esterilizada.",
      "Añada las pasas (starter de fermentación natural).",
      "Tape sin apretar demasiado y deje en lugar fresco de 24 a 36 horas.",
      "Retire las pasas, lleve a la nevera de 4 a 6 h y sirva frío en copas.",
    ],
    dicaBeatriz:
      "Esta bebida no tiene alcohol — pero tiene el alma del vino: el ritual de servir en copas, el gesto de levantar el cáliz, la profundidad de las especias. Úsela en cenas de familia, bautismos, Pascua. Toda la familia puede compartir una copa.",
    beneficios: [
      "Resveratrol de la uva antioxidante",
      "Canela y clavo antiinflamatorios",
      "Cero alcohol",
    ],
  },
};
