import lentilhas from "@/assets/recipe-lentilhas.jpg";
import peixe from "@/assets/recipe-peixe.jpg";
import salada from "@/assets/recipe-salada.jpg";
import pao from "@/assets/recipe-pao.jpg";
import sopa from "@/assets/recipe-sopa.jpg";
import figos from "@/assets/recipe-figos.jpg";
import suco from "@/assets/suco-sagrado.jpg";
import type { Lang } from "./i18n";
import { recipeTranslationsES } from "./recipes-es";
import { loadOverrides } from "./admin-store";
import { getCachedImages } from "./image-store";

// Only use verified Unsplash IDs (confirmed visible in screenshots)
const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&q=80`;

export type Categoria =
  | "Pratos Principais"
  | "Saladas e Acompanhamentos"
  | "Sopas"
  | "Ervas e Temperos"
  | "Sobremesas"
  | "Receitas Âncora";

export interface Receita {
  id: string;
  titulo: string;
  categoria: Categoria;
  versiculo: string;
  descricao: string;
  ingredientes: string[];
  preparo: string[];
  dicaBeatriz: string;
  beneficios: string[];
  imagem: string;
  tempo: number;
  rendimento: string;
  dificuldade: "Fácil" | "Médio" | "Avançado";
}

export const recipes: Receita[] = [
  // ── PRATOS PRINCIPAIS ───────────────────────────────────────────────
  {
    id: "lentilhas-esau",
    titulo: "Lentilhas de Esaú com Cebola Dourada",
    categoria: "Pratos Principais",
    versiculo: "Gênesis 25:34",
    descricao:
      "Então Jacó deu a Esaú pão e o guisado de lentilhas; e ele comeu, e bebeu, e levantou-se, e foi-se.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Fácil",
    imagem: lentilhas,
    ingredientes: [
      "300 g de lentilhas marrons secas",
      "2 cebolas médias em fatias finas",
      "4 dentes de alho picados",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho em pó",
      "1 colher de chá de páprica doce",
      "1 folha de louro",
      "1 colher de sopa de salsa fresca picada",
      "1 colher de sopa de coentro fresco picado",
      "Sal e pimenta-do-reino a gosto",
      "1 litro de água",
    ],
    preparo: [
      "Lave as lentilhas em água corrente e reserve.",
      "Aqueça 2 colheres de azeite em fogo médio. Refogue as cebolas lentamente por 15 minutos, mexendo de vez em quando, até dourarem.",
      "Junte o alho e refogue por mais 1 minuto.",
      "Acrescente o cominho e a páprica. Mexa 30 segundos para liberar os aromas.",
      "Adicione as lentilhas, a água e o louro. Tempere com sal e pimenta.",
      "Cozinhe em fogo baixo, panela parcialmente tampada, por 25 a 30 minutos até as lentilhas ficarem macias e o caldo encorpado.",
      "Retire o louro. Finalize com o azeite restante, salsa e coentro frescos.",
      "Sirva quente, com pão de fermentação natural.",
    ],
    dicaBeatriz:
      "Não pule o tempo da cebola. É o segredo deste prato. Cebola dourada lentamente é o que transforma uma sopa comum no guisado que fez um irmão trocar sua herança.",
    beneficios: [
      "Rica em proteína vegetal",
      "Fonte de ferro e fibras",
      "Anti-inflamatório natural",
    ],
  },
  {
    id: "peixe-galileia",
    titulo: "Peixe da Galileia ao Azeite e Alecrim",
    categoria: "Pratos Principais",
    versiculo: "Marcos 8:6",
    descricao: "E tomando-os, deu-os aos seus discípulos para que os pusessem diante deles.",
    rendimento: "4 porções",
    tempo: 25,
    dificuldade: "Fácil",
    imagem: peixe,
    ingredientes: [
      "4 filés de peixe branco (tilápia, pescada ou robalo) — 150 g cada",
      "4 colheres de sopa de azeite extravirgem",
      "3 dentes de alho amassados",
      "2 ramos de alecrim fresco",
      "1 limão (suco e raspas)",
      "1 colher de chá de sal grosso",
      "Pimenta-do-reino moída na hora",
      "Folhas de manjericão fresco para finalizar",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Tempere os filés com sal, pimenta, suco e raspas de limão. Deixe descansar 10 minutos.",
      "Espalhe metade do azeite numa assadeira e arrume os filés lado a lado.",
      "Distribua o alho amassado sobre os filés e regue com o azeite restante.",
      "Coloque os ramos de alecrim sobre os filés.",
      "Leve ao forno por 12 a 15 minutos, até o peixe estar opaco e desmanchar facilmente com um garfo.",
      "Finalize com folhas frescas de manjericão rasgadas.",
      "Sirva com arroz integral ou pão de fermentação natural.",
    ],
    dicaBeatriz:
      "O peixe está pronto quando a carne fica branca e solta em lascas. Mais um minuto no forno e ele resseca. Confie no seu olho, não no relógio.",
    beneficios: ["Rico em ômega-3", "Anti-inflamatório", "Proteína magra e de fácil digestão"],
  },
  {
    id: "cevada-grao-de-bico",
    titulo: "Cevada com Grão-de-Bico e Cominho",
    categoria: "Pratos Principais",
    versiculo: "Rute 2:14",
    descricao:
      "E disse-lhe Boaz à hora de comer: Achega-te aqui, e come do pão, e molha o teu bocado no vinagre.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Fácil",
    imagem: lentilhas,
    ingredientes: [
      "200 g de cevada em grão",
      "200 g de grão-de-bico seco (molho de 12 h na véspera)",
      "1 cebola média picada",
      "3 dentes de alho picados",
      "1 colher de sopa de cominho em grão",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de açafrão-da-terra (cúrcuma)",
      "1 colher de sopa de salsa fresca picada",
      "Sal e pimenta-do-reino a gosto",
      "1,2 litros de água ou caldo de legumes",
    ],
    preparo: [
      "Escorra o grão-de-bico do molho e reserve.",
      "Aqueça o azeite em fogo médio. Tueste o cominho em grão por 30 segundos.",
      "Adicione a cebola e refogue por 5 minutos. Junte o alho e refogue mais 1 minuto.",
      "Acrescente a cevada e o grão-de-bico, mexendo para envolver com o azeite.",
      "Tempere com sal, pimenta e açafrão-da-terra.",
      "Adicione a água quente e cozinhe em fogo baixo, panela parcialmente tampada, por cerca de 45 minutos, até tudo ficar macio.",
      "Acrescente mais água quente se necessário durante o cozimento.",
      "Finalize com salsa fresca e um fio generoso de azeite cru.",
    ],
    dicaBeatriz:
      "Cevada e grão-de-bico cozinham em tempos diferentes — por isso o segredo está em deixar o grão-de-bico de molho por uma noite inteira. Sem esse passo, ele fica duro enquanto a cevada se desfaz.",
    beneficios: [
      "Energia estável e de longa duração",
      "Rico em fibras prebióticas",
      "Reduz picos de glicemia",
    ],
  },
  {
    id: "pao-sirio-legumes",
    titulo: "Pão Sírio Recheado com Legumes Assados",
    categoria: "Pratos Principais",
    versiculo: "Mateus 4:4",
    descricao: "Não só de pão viverá o homem, mas de toda palavra que sai da boca de Deus.",
    rendimento: "4 porções",
    tempo: 40,
    dificuldade: "Fácil",
    imagem: pao,
    ingredientes: [
      "4 pães sírios integrais",
      "1 berinjela média em rodelas",
      "1 abobrinha média em rodelas",
      "1 pimentão vermelho em tiras",
      "1 cebola roxa em rodelas grossas",
      "1 tomate maduro em rodelas",
      "4 colheres de sopa de azeite extravirgem",
      "2 colheres de sopa de homus",
      "1 colher de chá de orégano",
      "1 colher de chá de tomilho seco",
      "Sal e pimenta a gosto",
      "Folhas de hortelã fresca",
    ],
    preparo: [
      "Preaqueça o forno a 220 °C.",
      "Espalhe os legumes numa assadeira sem amontoar. Regue com 3 colheres de azeite, orégano, tomilho, sal e pimenta. Misture com as mãos.",
      "Asse por 25 minutos, virando na metade, até dourarem nas bordas.",
      "Aqueça os pães sírios por 1 minuto em frigideira seca.",
      "Abra cada pão e passe homus na parte interna.",
      "Recheie com os legumes assados, tomate cru e folhas de hortelã.",
      "Regue com o azeite restante e sirva imediatamente.",
    ],
    dicaBeatriz:
      "Os legumes assados ficam na geladeira por até 3 dias. Faça o dobro no domingo e tenha o recheio pronto para a semana inteira. É a refeição mais rápida que existe.",
    beneficios: [
      "Refeição completa e equilibrada",
      "Fibras e vitaminas dos legumes",
      "Sem ultraprocessados",
    ],
  },
  {
    id: "tilapia-hortela",
    titulo: "Tilápia Grelhada ao Molho de Hortelã e Limão",
    categoria: "Pratos Principais",
    versiculo: "2 Crônicas 31:5",
    descricao: "E pão da terra fartamente, e azeite, e doçura, e tudo o que produz a abelha.",
    rendimento: "4 porções",
    tempo: 20,
    dificuldade: "Fácil",
    imagem: u("photo-1467003909585-2f8a72700288"),
    ingredientes: [
      "4 filés de tilápia — 150 g cada",
      "2 colheres de sopa de azeite extravirgem",
      "1 limão (suco)",
      "Sal e pimenta a gosto",
      "— Para o molho —",
      "4 colheres de sopa de iogurte natural integral",
      "1 colher de sopa de azeite",
      "2 colheres de sopa de hortelã fresca picada",
      "1 dente de alho amassado",
      "1 limão (suco e raspas)",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Tempere os filés com sal, pimenta e suco de limão. Deixe descansar 5 minutos.",
      "Misture todos os ingredientes do molho numa tigela. Reserve.",
      "Aqueça uma frigideira antiaderente em fogo médio-alto. Adicione o azeite.",
      "Coloque os filés e grelhe por 3 minutos de cada lado sem mexer.",
      "Transfira para os pratos.",
      "Sirva com uma colherada generosa do molho de hortelã por cima.",
    ],
    dicaBeatriz:
      "Não vire o peixe antes da hora. A pele dourada só se forma quando você deixa quieto por pelo menos 3 minutos. Paciência, querida.",
    beneficios: [
      "Baixo em gordura saturada",
      "Probiótico natural (iogurte)",
      "Anti-inflamatório (hortelã)",
    ],
  },
  {
    id: "mujadara",
    titulo: "Mujadara — Arroz Integral com Lentilha",
    categoria: "Pratos Principais",
    versiculo: "Provérbios 13:25",
    descricao:
      "O justo come para satisfazer o seu apetite, mas o estômago dos ímpios sofre necessidade.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Fácil",
    imagem: lentilhas,
    ingredientes: [
      "200 g de lentilhas marrons",
      "200 g de arroz integral",
      "3 cebolas grandes em fatias finas",
      "4 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho em pó",
      "1 colher de chá de canela em pó",
      "1 folha de louro",
      "Sal e pimenta-do-reino a gosto",
      "750 ml de água",
      "Salsa fresca picada para finalizar",
    ],
    preparo: [
      "Cozinhe as lentilhas em 500 ml de água com sal e louro por 15 minutos. Escorra e guarde o caldo.",
      "Refogue o arroz integral em 1 colher de azeite por 1 minuto.",
      "Acrescente as lentilhas, cominho, canela, sal e pimenta. Mexa.",
      "Adicione o caldo das lentilhas + água quente até completar 600 ml de líquido.",
      "Cozinhe em fogo baixo, panela tampada, por 35 a 40 minutos.",
      "Enquanto isso, caramelize as cebolas no azeite restante em fogo médio-baixo por 25 a 30 minutos.",
      "Sirva o arroz com lentilha coberto pela cebola caramelizada e salsa fresca.",
    ],
    dicaBeatriz:
      "A cebola caramelizada é o coração deste prato. Não tente acelerar com fogo alto — vai queimar e amargar. Caramelizar leva tempo, e o tempo é parte do milagre.",
    beneficios: [
      "Proteína completa (arroz + lentilha)",
      "Saciedade prolongada",
      "Zero ultraprocessado",
    ],
  },
  {
    id: "file-peixe-tomate",
    titulo: "Filé de Peixe ao Forno com Tomate e Manjericão",
    categoria: "Pratos Principais",
    versiculo: "Salmos 23:1-2",
    descricao: "O Senhor é o meu pastor, nada me faltará. Deitar-me faz em verdes pastos.",
    rendimento: "4 porções",
    tempo: 35,
    dificuldade: "Fácil",
    imagem: u("photo-1519708227418-c8fd9a32b7a2"),
    ingredientes: [
      "4 filés de peixe branco firme (tilápia, pescada ou merluza)",
      "4 tomates maduros sem pele em cubos",
      "1 cebola média picada",
      "4 dentes de alho fatiados",
      "4 colheres de sopa de azeite extravirgem",
      "1 maço de manjericão fresco",
      "1 colher de chá de orégano seco",
      "Sal e pimenta a gosto",
      "1 limão em rodelas",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Refogue a cebola em 2 colheres de azeite por 5 minutos. Adicione o alho e refogue 1 minuto.",
      "Junte os tomates, sal, pimenta e orégano. Cozinhe 8 minutos até formar molho rústico.",
      "Tempere os filés com sal, pimenta e suco de meio limão.",
      "Espalhe o molho de tomate numa travessa refratária. Acomode os filés por cima.",
      "Disponha rodelas de limão sobre o peixe e regue com o azeite restante.",
      "Leve ao forno por 15 a 18 minutos.",
      "Retire e finalize com manjericão fresco rasgado com as mãos.",
    ],
    dicaBeatriz:
      "Não corte o manjericão com a faca. Rasgue com as mãos, sempre. A faca oxida as folhas e mata o aroma em segundos. Esse é um daqueles segredos que mudam tudo sem custar nada.",
    beneficios: [
      "Licopeno do tomate contra inflamação",
      "Ômega-3 do peixe branco",
      "Antioxidante (manjericão)",
    ],
  },
  {
    id: "grao-de-bico-crocante-pp",
    titulo: "Grão-de-Bico Assado com Páprica e Ervas",
    categoria: "Pratos Principais",
    versiculo: "Levítico 23:14",
    descricao:
      "E pão e grão tostado e espigas verdes não comereis até aquele mesmo dia em que trouxerdes a oferta do vosso Deus.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "400 g de grão-de-bico cozido (bem escorrido e seco)",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de páprica defumada",
      "1 colher de chá de páprica doce",
      "1 colher de chá de cominho em pó",
      "1 colher de chá de orégano seco",
      "1 dente de alho amassado",
      "1 colher de chá de sal",
      "Pimenta-do-reino a gosto",
      "Suco de meio limão para finalizar",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Seque muito bem o grão-de-bico com um pano limpo. Esta etapa é essencial para a crocância.",
      "Misture o grão-de-bico com o azeite e todos os temperos. Mexa bem.",
      "Espalhe em assadeira com papel manteiga, em camada única sem amontoar.",
      "Asse por 35 a 40 minutos, mexendo a cada 10 minutos, até ficarem dourados.",
      "Retire do forno, regue com o suco de limão.",
      "Sirva quente como prato principal ou em temperatura ambiente como petisco.",
    ],
    dicaBeatriz:
      "Sequedade é tudo aqui. Grão-de-bico molhado nunca fica crocante — ele cozinha no próprio vapor e fica mole. Use o pano de prato. Confie em mim.",
    beneficios: ["Proteína vegetal completa", "Fibras para saciedade", "Sem gordura trans"],
  },
  {
    id: "frango-ervas",
    titulo: "Frango Assado com Ervas do Campo e Azeite",
    categoria: "Pratos Principais",
    versiculo: "Mateus 23:37",
    descricao: "Como faz a galinha aos seus pintinhos debaixo das asas.",
    rendimento: "4–6 porções",
    tempo: 90,
    dificuldade: "Médio",
    imagem: u("photo-1467003909585-2f8a72700288"),
    ingredientes: [
      "1 frango inteiro — cerca de 1,5 kg",
      "5 colheres de sopa de azeite extravirgem",
      "6 dentes de alho amassados",
      "2 ramos grandes de alecrim fresco",
      "1 maço de tomilho fresco",
      "2 limões",
      "1 cebola grande em quartos",
      "1 colher de sopa de sal grosso",
      "Pimenta-do-reino moída na hora",
      "1 colher de chá de páprica doce",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Misture o azeite, alho amassado, suco de 1 limão, sal, pimenta e páprica numa tigela.",
      "Lave e seque o frango com papel toalha por dentro e por fora.",
      "Esfregue a mistura de azeite por todo o frango, por dentro e sob a pele do peito.",
      "Recheie a cavidade com o 2.° limão em quartos, a cebola, o alecrim e o tomilho.",
      "Coloque na assadeira com o peito para cima.",
      "Asse por 1 hora a 1 hora e 15 minutos, regando a cada 20 minutos, até a pele dourar.",
      "Deixe descansar 10 minutos antes de cortar.",
    ],
    dicaBeatriz:
      "O descanso de 10 minutos depois do forno não é opcional — é o que mantém o frango suculento. Se você corta direto, todo o caldo escorre e a carne resseca. Reze um pai-nosso enquanto espera.",
    beneficios: [
      "Proteína magra de alta qualidade",
      "Ervas com propriedades antimicrobianas",
      "Sem conservantes",
    ],
  },
  {
    id: "quibe-assado",
    titulo: "Quibe Assado de Trigo Integral com Hortelã",
    categoria: "Pratos Principais",
    versiculo: "Gênesis 18:8",
    descricao:
      "E ele tomou manteiga e leite, e a vitela que tinha preparado, e pô-lo diante deles.",
    rendimento: "6 porções",
    tempo: 60,
    dificuldade: "Médio",
    imagem: lentilhas,
    ingredientes: [
      "300 g de trigo para quibe (fino)",
      "500 g de carne moída magra (patinho)",
      "1 cebola grande ralada",
      "1 maço de hortelã fresca picada",
      "1 colher de sopa de canela em pó",
      "1 colher de chá de pimenta síria",
      "4 colheres de sopa de azeite extravirgem",
      "Sal a gosto",
      "1 limão (suco)",
      "Água gelada para hidratar o trigo",
    ],
    preparo: [
      "Cubra o trigo com água gelada e deixe hidratar 30 minutos. Escorra e esprema bem com as mãos.",
      "Preaqueça o forno a 200 °C.",
      "Misture o trigo, carne moída, cebola, hortelã, canela, pimenta, sal e suco de limão.",
      "Sove a massa com as mãos por 5 minutos até ficar homogênea.",
      "Unte uma assadeira com 1 colher de azeite. Espalhe a massa uniformemente.",
      "Marque a superfície em losangos com uma faca.",
      "Regue com o azeite restante e leve ao forno por 35 a 40 minutos até dourar.",
      "Sirva morno ou frio, com iogurte natural ao lado.",
    ],
    dicaBeatriz:
      "A diferença entre um quibe seco e um quibe perfeito está em espremer bem o trigo. Aperte com as mãos até quase nenhuma água escorrer. Esse é o segredo que toda mãe libanesa ensina à filha.",
    beneficios: [
      "Trigo integral rico em fibras",
      "Hortelã com ação digestiva",
      "Ferro da carne magra",
    ],
  },
  {
    id: "lentilha-estufada",
    titulo: "Lentilha Estufada com Legumes da Estação",
    categoria: "Pratos Principais",
    versiculo: "Gênesis 3:18",
    descricao: "Comerás a erva do campo.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Fácil",
    imagem: u("photo-1547592180-85f173990554"),
    ingredientes: [
      "250 g de lentilhas marrons",
      "2 cenouras em rodelas",
      "1 abobrinha em cubos",
      "1 batata-doce média em cubos",
      "1 cebola grande picada",
      "3 dentes de alho picados",
      "2 tomates maduros em cubos",
      "3 colheres de sopa de azeite extravirgem",
      "1 folha de louro, cominho e páprica doce a gosto",
      "Sal e pimenta a gosto",
      "1 colher de sopa de salsa fresca picada",
      "1 litro de água ou caldo de legumes",
    ],
    preparo: [
      "Refogue a cebola no azeite por 5 minutos. Adicione o alho.",
      "Acrescente os tomates e cozinhe 5 minutos.",
      "Junte as lentilhas, louro, cominho, páprica, sal, pimenta. Misture.",
      "Adicione a cenoura, batata-doce e a água. Cozinhe em fogo baixo por 25 minutos.",
      "Acrescente a abobrinha e cozinhe mais 10 a 15 minutos até tudo ficar macio.",
      "Finalize com azeite cru e salsa fresca.",
      "Sirva sozinho ou com arroz integral.",
    ],
    dicaBeatriz:
      "A abobrinha entra por último porque cozinha mais rápido. Se colocar tudo junto, ela vira papa enquanto a cenoura ainda está dura. Cada legume tem o seu tempo. Respeite isso.",
    beneficios: ["Vitaminas A e C dos legumes", "Batata-doce antioxidante", "Refeição sem glúten"],
  },
  {
    id: "salmao-endro",
    titulo: "Salmão ao Forno com Endro e Limão",
    categoria: "Pratos Principais",
    versiculo: "Mateus 23:23",
    descricao: "Dais o dízimo da hortelã, do endro e do cominho.",
    rendimento: "4 porções",
    tempo: 25,
    dificuldade: "Fácil",
    imagem: peixe,
    ingredientes: [
      "4 postas de salmão — 150 g cada",
      "3 colheres de sopa de azeite extravirgem",
      "1 maço de endro fresco — 30 g",
      "2 limões",
      "3 dentes de alho fatiados",
      "1 colher de chá de sal grosso",
      "Pimenta-do-reino moída na hora",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Tempere o salmão com sal, pimenta e suco de 1 limão. Deixe 10 minutos.",
      "Espalhe 1 colher de azeite na assadeira. Acomode o salmão.",
      "Cubra cada posta com alho fatiado e ramos generosos de endro fresco.",
      "Disponha rodelas do segundo limão sobre o salmão e regue com o azeite restante.",
      "Leve ao forno por 12 a 15 minutos até a carne ficar opaca por fora mas ainda rosada no centro.",
      "Sirva com salada ou arroz integral.",
    ],
    dicaBeatriz:
      "Salmão tem um ponto certo — e ele é mais cedo do que você imagina. Quando você espeta um garfo e a carne começa a se soltar em lascas mas ainda parece úmida no meio, está pronto.",
    beneficios: ["Maior fonte de ômega-3", "Anti-inflamatório celular", "Vitamina D e B12"],
  },
  {
    id: "berinjela-recheada",
    titulo: "Berinjela Recheada com Grãos e Ervas",
    categoria: "Pratos Principais",
    versiculo: "Gênesis 1:29",
    descricao:
      "Eis que vos tenho dado toda a erva que dá semente, que está sobre a face de toda a terra.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Médio",
    imagem: salada,
    ingredientes: [
      "2 berinjelas grandes",
      "200 g de grão-de-bico cozido",
      "100 g de quinoa cozida (ou arroz integral)",
      "1 cebola média picada",
      "3 dentes de alho picados",
      "2 tomates maduros em cubos",
      "1 colher de sopa de hortelã fresca picada",
      "1 colher de sopa de salsa fresca picada",
      "1 colher de chá de cominho, 1 de canela",
      "4 colheres de sopa de azeite extravirgem",
      "30 g de nozes picadas",
      "Sal, pimenta e suco de 1 limão",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Corte as berinjelas ao meio e retire a polpa com colher, deixando casca de 1 cm. Pique a polpa.",
      "Tempere as cascas com sal, regue com azeite e asse 15 minutos.",
      "Refogue a cebola no azeite. Adicione o alho e a polpa picada. Refogue 5 minutos.",
      "Acrescente os tomates, grão-de-bico, quinoa, cominho, canela, sal e pimenta. Cozinhe 5 minutos.",
      "Retire do fogo. Misture as ervas frescas, nozes e suco de limão.",
      "Recheie as cascas, regue com azeite e volte ao forno por 15 minutos.",
      "Sirva morna.",
    ],
    dicaBeatriz:
      "Não jogue fora a polpa. Ela é o coração do recheio. Cada berinjela tem dentro de si o que precisa para se tornar prato completo — só precisa ser organizada de novo.",
    beneficios: ["Proteína completa vegetal", "Antioxidante (berinjela)", "Ômega-3 das nozes"],
  },

  // ── SALADAS E ACOMPANHAMENTOS ────────────────────────────────────────
  {
    id: "salada-profeta",
    titulo: "Salada do Profeta — Folhas, Romã e Nozes",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Deuteronômio 8:8",
    descricao: "Terra de trigo e cevada, de vides e figueiras e romeiras.",
    rendimento: "4 porções",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: salada,
    ingredientes: [
      "200 g de folhas verdes variadas (rúcula, alface-romana, espinafre baby)",
      "1 romã grande (sementes)",
      "50 g de nozes em pedaços",
      "1 cebola roxa pequena em fatias finas",
      "50 g de queijo branco fresco esfarelado (opcional)",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de sopa de vinagre de maçã",
      "1 colher de chá de mel",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Lave e seque bem as folhas. Disponha em travessa larga.",
      "Distribua a cebola roxa em fatias sobre as folhas.",
      "Espalhe as sementes de romã por toda a salada.",
      "Polvilhe as nozes e o queijo branco.",
      "Misture o azeite, vinagre, mel, sal e pimenta. Bata com garfo até emulsionar.",
      "Regue na hora de servir.",
      "Sirva imediatamente.",
    ],
    dicaBeatriz:
      "Para tirar as sementes da romã sem bagunça, corte ao meio e bata as costas com colher de pau, segurando sobre uma tigela. As sementes caem sozinhas.",
    beneficios: [
      "Polifenóis da romã anticâncer",
      "Ômega-3 das nozes",
      "Vitaminas K e A das folhas",
    ],
  },
  {
    id: "homus-tradicional",
    titulo: "Homus Tradicional ao Azeite",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "2 Crônicas 31:5",
    descricao: "Pão da terra fartamente, e azeite, e doçura.",
    rendimento: "6 porções",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: u("photo-1574181611642-d85c70c2ff81"),
    ingredientes: [
      "400 g de grão-de-bico cozido (com caldo reservado)",
      "3 colheres de sopa de tahine",
      "1 limão grande (suco)",
      "2 dentes de alho",
      "4 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho em pó",
      "Sal a gosto",
      "Páprica doce e salsa fresca para finalizar",
    ],
    preparo: [
      "No liquidificador, coloque o grão-de-bico, tahine, suco de limão, alho, cominho e sal.",
      "Bata por 1 minuto, adicionando o caldo do grão-de-bico aos poucos até obter pasta cremosa.",
      "Adicione 2 colheres de azeite e bata mais 30 segundos.",
      "Prove e ajuste sal e limão.",
      "Transfira para prato fundo. Com as costas de uma colher, faça espirais na superfície.",
      "Regue com o azeite restante, polvilhe páprica e salsa.",
      "Sirva com pão sírio integral ou legumes crus.",
    ],
    dicaBeatriz:
      "O caldo do cozimento do grão-de-bico é o segredo da cremosidade. Nunca jogue fora. Se usar de conserva, troque pelo líquido da lata (aquafaba). Faz diferença.",
    beneficios: [
      "Proteína e fibra do grão-de-bico",
      "Cálcio e ferro do tahine",
      "Gordura boa do azeite",
    ],
  },
  {
    id: "babaganuche",
    titulo: "Babaganuche — Pasta de Berinjela Assada",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Gênesis 3:18",
    descricao: "Comerás a erva do campo.",
    rendimento: "4 porções",
    tempo: 45,
    dificuldade: "Fácil",
    imagem: salada,
    ingredientes: [
      "2 berinjelas grandes",
      "3 colheres de sopa de tahine",
      "1 limão grande (suco)",
      "2 dentes de alho amassados",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho em pó",
      "Sal a gosto",
      "Salsa picada e gergelim tostado para finalizar",
    ],
    preparo: [
      "Preaqueça o forno a 220 °C.",
      "Fure as berinjelas com garfo. Leve ao forno por 40 minutos virando na metade.",
      "Retire e deixe esfriar. Corte ao meio e retire a polpa com colher.",
      "Coloque a polpa numa peneira por 5 minutos para escorrer o excesso de líquido.",
      "Amasse a polpa com garfo (não use processador — textura rústica é parte do prato).",
      "Misture o tahine, limão, alho, cominho, 2 colheres de azeite e sal.",
      "Transfira para prato, regue com azeite restante, salsa e gergelim.",
    ],
    dicaBeatriz:
      "Se tiver fogão a gás, queime a berinjela diretamente na chama antes de ir ao forno. O sabor defumado fica mil vezes mais intenso. É como minha avó fazia.",
    beneficios: ["Fibras e antioxidantes da berinjela", "Cálcio do gergelim", "Anti-inflamatório"],
  },
  {
    id: "tabule",
    titulo: "Tabule de Trigo Grosso, Hortelã e Tomate",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Gênesis 1:29",
    descricao: "Eis que vos tenho dado toda a erva que dá semente.",
    rendimento: "4 porções",
    tempo: 30,
    dificuldade: "Fácil",
    imagem: u("photo-1529563021893-cc83c992d75d"),
    ingredientes: [
      "150 g de trigo para quibe (fino)",
      "4 tomates maduros e firmes em cubos pequenos",
      "1 maço grande de salsa fresca — 80 g",
      "1 maço médio de hortelã fresca — 30 g",
      "1 cebola roxa pequena em cubos bem pequenos",
      "1 pepino médio em cubos",
      "5 colheres de sopa de azeite extravirgem",
      "2 limões (suco)",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Cubra o trigo com água gelada e deixe hidratar 20 minutos. Escorra e esprema.",
      "Pique a salsa e hortelã muito finamente.",
      "Misture o trigo, tomates, pepino, cebola, salsa e hortelã.",
      "Tempere com limão, azeite, sal e pimenta.",
      "Misture delicadamente com as mãos.",
      "Leve à geladeira por 15 minutos antes de servir.",
      "Sirva como acompanhamento ou em folhas de alface.",
    ],
    dicaBeatriz:
      "Tabule de verdade tem mais erva do que trigo. Se você olhar e ver mais trigo do que verde, voltou a fazer salada de trigo. Coragem com as ervas. O verde é o protagonista.",
    beneficios: [
      "Vitamina C da salsa (9× mais que limão)",
      "Digestivo (hortelã)",
      "Fibras do trigo integral",
    ],
  },
  {
    id: "pepino-iogurte",
    titulo: "Salada de Pepino com Iogurte e Hortelã",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Números 11:5",
    descricao: "Lembramo-nos dos peixes que comíamos no Egito de graça, dos pepinos, e dos melões.",
    rendimento: "4 porções",
    tempo: 10,
    dificuldade: "Fácil",
    imagem: u("photo-1565557623262-b51c2513a641"),
    ingredientes: [
      "2 pepinos médios em cubos pequenos",
      "300 g de iogurte natural integral (sem açúcar)",
      "1 colher de sopa de hortelã fresca picada",
      "1 dente de alho amassado",
      "2 colheres de sopa de azeite extravirgem",
      "Sal e pimenta a gosto",
      "Folhas extras de hortelã para finalizar",
    ],
    preparo: [
      "Corte o pepino, polvilhe sal e deixe escorrer por 10 minutos numa peneira.",
      "Misture o iogurte, alho, hortelã, azeite, sal e pimenta.",
      "Acrescente os cubos de pepino escorridos.",
      "Misture delicadamente e transfira para travessa.",
      "Finalize com hortelã fresca e fio de azeite.",
      "Sirva gelada.",
    ],
    dicaBeatriz:
      "Esta é a companhia perfeita para pratos quentes e apimentados. O iogurte e o pepino refrescam o paladar e o estômago. Sirva ao lado de quibe, lentilha estufada ou frango assado.",
    beneficios: [
      "Probiótico natural (iogurte)",
      "Hidratante (pepino 96% água)",
      "Digestivo (hortelã)",
    ],
  },
  {
    id: "cenoura-mel",
    titulo: "Cenoura Assada com Mel e Cominho",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Provérbios 24:13",
    descricao: "Come mel, meu filho, porque é bom, e o favo de mel é doce ao teu paladar.",
    rendimento: "4 porções",
    tempo: 40,
    dificuldade: "Fácil",
    imagem: u("photo-1598170845058-32b9d6a5da37"),
    ingredientes: [
      "600 g de cenouras médias",
      "3 colheres de sopa de azeite extravirgem",
      "2 colheres de sopa de mel",
      "1 colher de chá de cominho em pó",
      "1 colher de chá de páprica doce",
      "Sal e pimenta a gosto",
      "1 colher de sopa de salsa fresca",
      "Sementes de gergelim para finalizar",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Se forem pequenas, deixe as cenouras inteiras; grandes, corte ao meio no comprimento.",
      "Misture azeite, mel, cominho, páprica, sal e pimenta.",
      "Envolva as cenouras com a mistura.",
      "Disponha em assadeira com papel manteiga sem amontoar.",
      "Asse por 30 a 35 minutos, virando na metade, até macias e caramelizadas.",
      "Finalize com salsa e gergelim.",
    ],
    dicaBeatriz:
      "Cenoura é uma das poucas raízes que ficam doces no forno sem açúcar. O mel só intensifica o doce natural. Sirva ao lado de carne, peixe ou ave e prepare-se: o prato volta vazio.",
    beneficios: [
      "Beta-caroteno (pró-vitamina A)",
      "Mel antimicrobiano natural",
      "Fibras para trânsito intestinal",
    ],
  },
  {
    id: "beterraba-endro",
    titulo: "Beterraba ao Azeite e Endro",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Mateus 23:23",
    descricao: "Dais o dízimo da hortelã, do endro e do cominho.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Fácil",
    imagem: salada,
    ingredientes: [
      "4 beterrabas médias",
      "4 colheres de sopa de azeite extravirgem",
      "2 colheres de sopa de vinagre de maçã",
      "1 maço pequeno de endro fresco — 20 g",
      "1 dente de alho amassado",
      "1 colher de chá de mel",
      "Sal e pimenta a gosto",
      "50 g de nozes (opcional)",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Envolva cada beterraba em papel-alumínio e leve ao forno por 50 minutos.",
      "Retire, deixe esfriar e descasque (a casca sai com facilidade).",
      "Corte em cubos ou rodelas.",
      "Misture o azeite, vinagre, alho, mel, sal e pimenta.",
      "Envolva a beterraba no molho junto com o endro picado.",
      "Transfira para travessa e finalize com nozes.",
      "Sirva morna ou em temperatura ambiente.",
    ],
    dicaBeatriz:
      "Beterraba assada com casca preserva todo o sabor doce e a textura aveludada. Cozinhada na água, fica aguada e perde o melhor. Vale a hora de forno.",
    beneficios: [
      "Nitratos para pressão e energia",
      "Betalaínas antioxidantes",
      "Ferro e ácido fólico",
    ],
  },
  {
    id: "lentilha-morna",
    titulo: "Salada Morna de Lentilha com Cebola Roxa",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Provérbios 13:25",
    descricao: "O justo come para satisfazer o seu apetite.",
    rendimento: "4 porções",
    tempo: 35,
    dificuldade: "Fácil",
    imagem: lentilhas,
    ingredientes: [
      "250 g de lentilhas marrons",
      "1 cebola roxa em fatias finas",
      "1 pimentão amarelo em cubos",
      "1 tomate maduro firme em cubos",
      "1 maço pequeno de salsa fresca",
      "4 colheres de sopa de azeite extravirgem",
      "2 colheres de sopa de vinagre de maçã",
      "1 colher de chá de mostarda dijon",
      "1 folha de louro",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Cozinhe as lentilhas com água e louro por 20 a 25 minutos até ficarem macias (não papa). Tempere com sal nos últimos 5 minutos.",
      "Escorra, descarte o louro e transfira para tigela grande.",
      "Ainda mornas, acrescente a cebola, pimentão e tomate.",
      "Misture o azeite, vinagre, mostarda, sal e pimenta. Bata com garfo.",
      "Despeje o molho sobre as lentilhas mornas.",
      "Acrescente a salsa e misture delicadamente.",
      "Sirva morna ou em temperatura ambiente.",
    ],
    dicaBeatriz:
      "Lentilha morna absorve o molho de um jeito que a lentilha fria não absorve. Por isso o tempero entra enquanto ainda está quente. Pequeno detalhe, grande diferença.",
    beneficios: [
      "Proteína vegetal de alta absorção",
      "Ferro não-heme + vitamina C",
      "Anti-inflamatório (cúrcuma/cebola)",
    ],
  },
  {
    id: "grao-crocante-salada",
    titulo: "Grão-de-Bico Crocante com Páprica",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Rute 3:7",
    descricao: "Comeu Boaz, e bebeu, e alegrou-se o seu coração.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "400 g de grão-de-bico cozido (bem escorrido)",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de páprica defumada",
      "1 colher de chá de páprica doce",
      "1 colher de chá de alho em pó",
      "1 colher de chá de cominho em pó",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Escorra o grão-de-bico, espalhe em pano limpo e seque completamente, removendo cascas soltas.",
      "Misture o azeite e todos os temperos.",
      "Envolva o grão-de-bico no tempero.",
      "Espalhe em assadeira com papel manteiga, em camada única.",
      "Asse por 40 a 45 minutos, mexendo a cada 10 minutos.",
      "Deixe esfriar 5 minutos na assadeira — fica ainda mais crocante ao esfriar.",
      "Sirva como petisco ou polvilhe sobre saladas.",
    ],
    dicaBeatriz:
      "A diferença entre crocante e mole é o pano de prato. Esses 5 minutos de trabalho são o que separa um lanche memorável de uma decepção.",
    beneficios: ["Proteína e fibra", "Petisco sem gordura trans", "Energia estável"],
  },
  {
    id: "salada-figos",
    titulo: "Salada de Figos Frescos, Queijo e Nozes",
    categoria: "Saladas e Acompanhamentos",
    versiculo: "Miqueias 4:4",
    descricao: "Cada um se assentará debaixo da sua videira e debaixo da sua figueira.",
    rendimento: "4 porções",
    tempo: 10,
    dificuldade: "Fácil",
    imagem: figos,
    ingredientes: [
      "6 figos maduros e firmes",
      "150 g de queijo branco fresco (ricota ou queijo de cabra)",
      "100 g de rúcula",
      "50 g de nozes em pedaços",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de sopa de mel",
      "1 colher de sopa de vinagre balsâmico (opcional)",
      "Sal e pimenta a gosto",
      "Folhas de hortelã fresca",
    ],
    preparo: [
      "Corte cada figo em 4 partes.",
      "Disponha a rúcula em travessa larga.",
      "Distribua os figos sobre as folhas.",
      "Esfarele o queijo e espalhe pela salada.",
      "Polvilhe as nozes.",
      "Misture azeite, mel, vinagre, sal e pimenta. Regue a salada.",
      "Finalize com hortelã fresca.",
    ],
    dicaBeatriz:
      "Figo fresco tem temporada curta. Quando estiver em época, faça esta salada o máximo que puder — é a mais bonita do livro. Fora de temporada, use figos secos hidratados em água morna por 10 minutos.",
    beneficios: ["Figo rico em potássio e fibra", "Antioxidantes da rúcula", "Ômega-3 das nozes"],
  },

  // ── SOPAS ────────────────────────────────────────────────────────────
  {
    id: "caldo-daniel",
    titulo: "Caldo de Daniel — Lentilha, Cenoura e Ervas",
    categoria: "Sopas",
    versiculo: "Daniel 1:12",
    descricao:
      "Experimenta, peço-te, dez dias os teus servos, e que se nos dêem legumes a comer, e água a beber.",
    rendimento: "4 porções",
    tempo: 45,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "250 g de lentilhas marrons",
      "2 cenouras médias em cubos",
      "1 cebola grande picada",
      "3 dentes de alho picados",
      "4 colheres de sopa de azeite extravirgem",
      "1 folha de louro",
      "1 colher de chá de cominho em pó",
      "1 colher de chá de açafrão-da-terra (cúrcuma)",
      "1 colher de sopa de salsa e coentro frescos picados",
      "1,2 litros de água ou caldo de legumes",
      "Sal e pimenta a gosto",
      "1 limão em quartos para servir",
    ],
    preparo: [
      "Lave bem as lentilhas e reserve.",
      "Aqueça 2 colheres de azeite. Refogue a cebola por 5 minutos.",
      "Acrescente o alho e refogue 2 minutos.",
      "Adicione o cominho e o açafrão-da-terra. Mexa 30 segundos.",
      "Junte as lentilhas, cenouras, louro e água quente. Tempere.",
      "Cozinhe em fogo baixo por 30 minutos.",
      "Para versão cremosa, bata metade no liquidificador e devolva à panela.",
      "Finalize com azeite restante e ervas frescas.",
      "Sirva com limão ao lado.",
    ],
    dicaBeatriz:
      "O limão ao servir não é decoração — é parte essencial. O suco cítrico ativa o ferro das lentilhas para o corpo absorver melhor. Pequeno gesto, grande diferença nutricional.",
    beneficios: [
      "Cúrcuma poderoso anti-inflamatório",
      "Ferro + vitamina C (absorção máxima)",
      "Fibras solúveis",
    ],
  },
  {
    id: "sopa-cevada",
    titulo: "Sopa de Cevada com Cogumelos",
    categoria: "Sopas",
    versiculo: "Mateus 13:31",
    descricao: "O reino dos céus é semelhante ao grão de mostarda.",
    rendimento: "4 porções",
    tempo: 75,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "200 g de cevada em grão",
      "300 g de cogumelos frescos fatiados (paris, shitake ou portobello)",
      "1 cebola grande picada",
      "3 dentes de alho picados",
      "2 cenouras em cubos",
      "4 colheres de sopa de azeite extravirgem",
      "1 folha de louro",
      "2 ramos de tomilho fresco",
      "1,5 litros de água ou caldo de legumes",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Lave a cevada e reserve.",
      "Refogue a cebola no azeite por 5 minutos. Adicione o alho.",
      "Junte os cogumelos fatiados. Refogue por 8 minutos até dourarem.",
      "Acrescente a cevada, cenouras, louro, tomilho e água quente.",
      "Tempere e cozinhe em fogo baixo por 50 minutos a 1 hora até a cevada ficar macia.",
      "Acrescente mais água quente se necessário.",
      "Retire o louro e o tomilho. Finalize com azeite e salsa.",
      "Sirva bem quente.",
    ],
    dicaBeatriz:
      "Não tenha pressa com os cogumelos. Refogue até dourarem — é nesse dourado que mora todo o sabor da sopa. Cogumelo refogado às pressas fica aguado, e sopa aguada de cogumelo é tristeza.",
    beneficios: [
      "Beta-glucanas da cevada (imunidade)",
      "Cogumelos ricos em vitamina D",
      "Prebiótico natural",
    ],
  },
  {
    id: "creme-abobora",
    titulo: "Creme de Abóbora com Gengibre",
    categoria: "Sopas",
    versiculo: "Gênesis 9:3",
    descricao:
      "Tudo o que tem vida e se move será para vosso mantimento; tudo vos tenho dado como a erva verde.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Fácil",
    imagem: u("photo-1476718406336-bb5a9690ee2a"),
    ingredientes: [
      "800 g de abóbora cabotiá descascada em cubos",
      "1 cebola grande picada",
      "3 dentes de alho picados",
      "1 pedaço de gengibre fresco de 3 cm, picado",
      "4 colheres de sopa de azeite extravirgem",
      "1 colher de chá de açafrão-da-terra",
      "1 colher de chá de cominho em pó",
      "1 litro de água ou caldo de legumes",
      "100 ml de leite de coco (opcional)",
      "Sal e pimenta a gosto",
      "Sementes de abóbora torradas e coentro para finalizar",
    ],
    preparo: [
      "Refogue a cebola no azeite por 5 minutos. Adicione o alho e gengibre.",
      "Acrescente o açafrão e cominho. Mexa 30 segundos.",
      "Junte a abóbora. Refogue 5 minutos.",
      "Adicione a água quente. Cozinhe em fogo baixo por 25 a 30 minutos.",
      "Bata no liquidificador até obter creme liso.",
      "Volte à panela. Acrescente leite de coco se quiser e aqueça 2 minutos.",
      "Sirva com azeite, sementes torradas e coentro.",
    ],
    dicaBeatriz:
      "O gengibre é o ingrediente que tira esta sopa do comum. Não pule e não diminua a quantidade — ele é responsável pelo calor que aquece de dentro e tem propriedades anti-inflamatórias poderosas.",
    beneficios: [
      "Gengibre anti-inflamatório e digestivo",
      "Beta-caroteno da abóbora",
      "Cúrcuma detox",
    ],
  },
  {
    id: "sopa-grao",
    titulo: "Sopa de Grão-de-Bico com Espinafre",
    categoria: "Sopas",
    versiculo: "Salmos 34:18",
    descricao: "O Senhor está perto dos que têm um coração contrito.",
    rendimento: "4 porções",
    tempo: 40,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "400 g de grão-de-bico cozido",
      "300 g de espinafre fresco",
      "1 cebola grande picada",
      "4 dentes de alho picados",
      "2 tomates maduros sem pele em cubos",
      "4 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho e páprica defumada",
      "1 limão (suco)",
      "1 litro de água quente",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Refogue a cebola no azeite. Adicione o alho.",
      "Acrescente cominho e páprica. Mexa 30 segundos.",
      "Junte os tomates e cozinhe 5 minutos.",
      "Adicione o grão-de-bico e a água quente. Cozinhe 15 minutos.",
      "Para encorpar, bata 1 concha no liquidificador e devolva.",
      "Acrescente o espinafre e cozinhe apenas 3 minutos.",
      "Finalize com suco de limão, azeite restante e salsa.",
    ],
    dicaBeatriz:
      "O espinafre entra por último, sempre. Espinafre que cozinha demais perde cor, ferro e vira comida velha. Três minutos de panela é tudo o que ele precisa.",
    beneficios: [
      "Ferro do espinafre + vitamina C (absorção dupla)",
      "Proteína completa",
      "Luteína para a visão",
    ],
  },
  {
    id: "caldo-verde",
    titulo: "Caldo Verde de Couve, Batata e Azeite",
    categoria: "Sopas",
    versiculo: "Gênesis 1:29",
    descricao: "Deus disse: Eis que vos dei toda a erva que dá semente.",
    rendimento: "4 porções",
    tempo: 40,
    dificuldade: "Fácil",
    imagem: u("photo-1518977676601-b53f82aba655"),
    ingredientes: [
      "600 g de batatas em cubos",
      "1 maço grande de couve-manteiga",
      "1 cebola grande picada",
      "4 dentes de alho picados",
      "5 colheres de sopa de azeite extravirgem",
      "1,2 litros de água",
      "Sal e pimenta a gosto",
      "Pimenta calabresa seca (opcional)",
    ],
    preparo: [
      "Refogue a cebola em 2 colheres de azeite. Adicione o alho.",
      "Acrescente as batatas. Refogue 3 minutos.",
      "Adicione a água quente, sal e pimenta. Cozinhe 20 minutos até as batatas ficarem macias.",
      "Corte a couve em tiras muito finas (chiffonade).",
      "Bata a sopa no liquidificador até obter creme liso. Volte à panela.",
      "Acrescente a couve e cozinhe apenas 2 a 3 minutos.",
      "Finalize com o azeite restante e pimenta calabresa.",
      "Sirva imediatamente, fumegante.",
    ],
    dicaBeatriz:
      "A couve cortada bem fina é o que faz o caldo verde de verdade. Couve grossa cozinha demais e perde a vivacidade. Quanto mais fino o corte, mais bonita e saborosa fica a sopa.",
    beneficios: [
      "Couve superalimento (vit. K, C, ferro)",
      "Batata fonte de energia",
      "Azeite anti-inflamatório",
    ],
  },
  {
    id: "sopa-tomate",
    titulo: "Sopa de Tomate Assado com Manjericão",
    categoria: "Sopas",
    versiculo: "Salmos 34:8",
    descricao: "Provai, e vede que o Senhor é bom.",
    rendimento: "4 porções",
    tempo: 60,
    dificuldade: "Fácil",
    imagem: u("photo-1603105037880-880cd4edfb0d"),
    ingredientes: [
      "1 kg de tomates maduros (italianos ou pera)",
      "1 cebola grande em quartos",
      "6 dentes de alho com casca",
      "5 colheres de sopa de azeite extravirgem",
      "1 colher de chá de orégano seco",
      "1 maço de manjericão fresco",
      "1 colher de sopa de mel",
      "800 ml de água quente",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Corte os tomates ao meio. Arrume em assadeira com a cebola e alho. Regue com azeite, orégano, sal e pimenta.",
      "Asse por 35 a 40 minutos até os tomates murcharem e queimarem nas pontas.",
      "Aperte os dentes de alho para soltar a polpa. Descarte as cascas.",
      "Bata tudo no liquidificador com metade do manjericão.",
      "Transfira para panela, adicione a água quente e o mel. Ajuste o sal.",
      "Aqueça 5 minutos sem ferver forte.",
      "Sirva com azeite, manjericão rasgado e pimenta moída.",
    ],
    dicaBeatriz:
      "O mel é o que faz esta sopa parecer profissional. Tomate tem acidez natural — quando você equilibra com um toque de doce, o sabor inteiro fica redondo. Truque de chef que toda dona de casa deve saber.",
    beneficios: [
      "Licopeno potenciado pelo calor do forno",
      "Mel antimicrobiano",
      "Manjericão adaptógeno",
    ],
  },
  {
    id: "sopa-feijao-branco",
    titulo: "Sopa de Feijão Branco com Alecrim",
    categoria: "Sopas",
    versiculo: "Isaías 58:11",
    descricao: "E saciar-te-á a tua alma.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Fácil",
    imagem: sopa,
    ingredientes: [
      "300 g de feijão branco seco (molho de 12 h)",
      "1 cebola grande picada",
      "4 dentes de alho picados",
      "2 cenouras em cubos pequenos",
      "4 colheres de sopa de azeite extravirgem",
      "2 ramos de alecrim fresco",
      "1 folha de louro",
      "1,5 litros de água quente",
      "Sal, pimenta e limão para finalizar",
    ],
    preparo: [
      "Escorra o feijão do molho.",
      "Refogue a cebola no azeite. Adicione alho e cenouras.",
      "Acrescente o feijão, alecrim, louro e água quente.",
      "Cozinhe em fogo baixo por 35 a 45 minutos. Adicione sal só nos últimos 10 minutos.",
      "Retire o louro e alecrim.",
      "Bata 1 a 2 conchas no liquidificador e devolva (o restante fica inteiro).",
      "Sirva com azeite, salsa e gotas de limão.",
    ],
    dicaBeatriz:
      "Sal no feijão é como falar com pressa: cedo demais estraga, no tempo certo transforma. Sempre nos últimos 10 minutos — esse segredo vale para todos os feijões deste livro.",
    beneficios: [
      "Fibras solúveis para colesterol",
      "Proteína vegetal completa",
      "Alecrim antioxidante e digestivo",
    ],
  },

  // ── ERVAS E TEMPEROS ─────────────────────────────────────────────────
  {
    id: "azeite-aromatizado",
    titulo: "Azeite Aromatizado com Alecrim e Alho",
    categoria: "Ervas e Temperos",
    versiculo: "Eclesiastes 7:1",
    descricao: "O bom nome é melhor do que o óleo precioso.",
    rendimento: "500 ml",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: u("photo-1474979266404-7eaacbcd87c5"),
    ingredientes: [
      "500 ml de azeite extravirgem",
      "4 ramos grandes de alecrim fresco",
      "6 dentes de alho levemente amassados (sem cortar)",
      "1 colher de chá de pimenta-do-reino em grão",
      "1 folha de louro",
    ],
    preparo: [
      "Lave e seque muito bem o alecrim. Qualquer gotinha de água pode estragar o azeite.",
      "Amasse levemente os dentes de alho com a lâmina da faca, sem cortar.",
      "Aqueça o azeite em fogo muito baixo por 3 minutos (não pode fritar).",
      "Retire do fogo e deixe esfriar 5 minutos.",
      "Coloque alecrim, alho, pimenta e louro numa garrafa de vidro esterilizada.",
      "Despeje o azeite morno por cima, cobrindo completamente.",
      "Tampe e deixe descansar em local fresco e escuro por 7 dias.",
      "Conserva-se em geladeira por até 1 mês.",
    ],
    dicaBeatriz:
      "Coloque uma etiqueta com a data de produção no vidro. Azeite aromatizado caseiro precisa ser consumido em até 30 dias — depois disso, ervas em imersão podem desenvolver bactérias.",
    beneficios: [
      "Polifenóis do azeite anti-inflamatórios",
      "Alicina do alho antibacteriana",
      "Alecrim antioxidante",
    ],
  },
  {
    id: "molho-hortela",
    titulo: "Molho de Hortelã e Iogurte",
    categoria: "Ervas e Temperos",
    versiculo: "Mateus 23:23",
    descricao: "Dais o dízimo da hortelã, do endro e do cominho.",
    rendimento: "300 g",
    tempo: 10,
    dificuldade: "Fácil",
    imagem: u("photo-1503764654157-72d979d9af2f"),
    ingredientes: [
      "300 g de iogurte natural integral (sem açúcar)",
      "1 maço pequeno de hortelã fresca — 20 g",
      "2 dentes de alho amassados",
      "2 colheres de sopa de azeite extravirgem",
      "1 colher de chá de suco de limão",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Lave a hortelã. Seque e retire apenas as folhas.",
      "Pique finamente com faca afiada (não use processador — oxida e amarga).",
      "Misture o iogurte, alho, hortelã, azeite, limão, sal e pimenta.",
      "Cubra e leve à geladeira por pelo menos 30 minutos.",
      "Conserva-se por até 3 dias na geladeira.",
    ],
    dicaBeatriz:
      "Sempre amasse o alho com o lado da faca antes de adicionar ao iogurte. Alho em cubos cria pontos amargos. Amassado, ele se distribui em sabor, não em mordida.",
    beneficios: ["Probiótico natural", "Hortelã digestiva e refrescante", "Cálcio do iogurte"],
  },
  {
    id: "pesto-biblico",
    titulo: "Pesto de Manjericão com Nozes",
    categoria: "Ervas e Temperos",
    versiculo: "Salmos 92:12",
    descricao: "O justo florescerá como a palmeira.",
    rendimento: "200 g",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: u("photo-1558618666-fcd25c85cd64"),
    ingredientes: [
      "80 g de folhas de manjericão fresco",
      "50 g de nozes",
      "3 dentes de alho",
      "1 limão (suco e raspas)",
      "150 ml de azeite extravirgem",
      "Sal grosso a gosto",
      "Pimenta-do-reino moída na hora",
    ],
    preparo: [
      "Lave o manjericão e seque muito bem. Retire apenas as folhas.",
      "Toste as nozes em frigideira seca por 3 minutos. Deixe esfriar.",
      "No processador, triture grosseiramente o alho, nozes e sal.",
      "Acrescente as folhas de manjericão e as raspas de limão. Pulse.",
      "Com o aparelho ligado, despeje o azeite em fio até obter pasta cremosa.",
      "Tempere com limão, sal e pimenta.",
      "Transfira para vidro esterilizado e cubra com fio de azeite.",
      "Conserva-se na geladeira por até 7 dias.",
    ],
    dicaBeatriz:
      "O segredo da cor verde-viva é não bater demais. Quanto mais tempo no processador, mais escuro e amargo fica. Triture em pulsos curtos. O pesto deve ter cor brilhante e textura rústica.",
    beneficios: [
      "Ômega-3 das nozes",
      "Basilicão com vitamina K e magnésio",
      "Antioxidante poderoso",
    ],
  },
  {
    id: "tahine-caseiro",
    titulo: "Tahine Puro Caseiro",
    categoria: "Ervas e Temperos",
    versiculo: "2 Samuel 9:7",
    descricao: "Comerás à mesa do rei continuamente.",
    rendimento: "250 g",
    tempo: 25,
    dificuldade: "Fácil",
    imagem: u("photo-1569050467447-ce54b3bbc37d"),
    ingredientes: [
      "300 g de sementes de gergelim branco",
      "3 a 5 colheres de sopa de azeite extravirgem (ou óleo neutro)",
      "Pitada de sal (opcional)",
    ],
    preparo: [
      "Preaqueça o forno a 150 °C.",
      "Espalhe o gergelim em assadeira em camada única.",
      "Toste por 10 a 12 minutos, mexendo na metade, até levemente dourado. Fique perto do forno — gergelim queima rápido.",
      "Deixe esfriar completamente (15 minutos).",
      "Triture no processador por 2 minutos. Raspe as laterais e continue por mais 2 minutos.",
      "Adicione o azeite 1 colher por vez até obter pasta lisa e cremosa.",
      "Conserva-se em geladeira por até 2 meses. Mexa antes de usar.",
    ],
    dicaBeatriz:
      "Tostar o gergelim é o que separa o tahine caseiro do industrializado. Sementes cruas dão pasta amarga. Tostadas viram aquela pasta dourada, rica, perfumada que faz qualquer prato especial.",
    beneficios: ["Cálcio (riquíssimo)", "Gorduras monoinsaturadas", "Proteína completa vegetal"],
  },
  {
    id: "molho-tahine",
    titulo: "Molho de Tahine com Limão e Alho",
    categoria: "Ervas e Temperos",
    versiculo: "2 Crônicas 31:5",
    descricao: "Pão da terra fartamente, e azeite, e doçura.",
    rendimento: "200 ml",
    tempo: 5,
    dificuldade: "Fácil",
    imagem: u("photo-1503764654157-72d979d9af2f"),
    ingredientes: [
      "4 colheres de sopa de tahine",
      "1 limão grande (suco)",
      "2 dentes de alho amassados",
      "2 colheres de sopa de azeite extravirgem",
      "1 colher de chá de cominho em pó",
      "1 colher de sopa de salsa fresca picada",
      "Sal a gosto",
      "Água gelada para ajustar a textura",
    ],
    preparo: [
      "Coloque o tahine, suco de limão e alho amassado numa tigela.",
      "Mexa com garfo — a mistura vai endurecer e ficar grumosa (normal).",
      "Continue mexendo, adicionando água gelada 1 colher por vez.",
      "Após 4 a 6 colheres de água, a textura vira creme liso.",
      "Acrescente o azeite, cominho, sal e salsa.",
      "Conserva-se na geladeira por até 5 dias.",
    ],
    dicaBeatriz:
      "A água precisa estar gelada. É o choque entre a água fria e o tahine que cria a emulsão cremosa. Água em temperatura ambiente não tem o mesmo efeito. Detalhe pequeno, diferença enorme.",
    beneficios: ["Cálcio e ferro do tahine", "Vitamina C do limão", "Digestivo (cominho)"],
  },
  {
    id: "vinagrete-ervas",
    titulo: "Vinagrete de Ervas do Campo",
    categoria: "Ervas e Temperos",
    versiculo: "Jeremias 17:7-8",
    descricao:
      "Bendito é o homem que se confia no Senhor, porque será como a árvore plantada junto às águas.",
    rendimento: "250 ml",
    tempo: 10,
    dificuldade: "Fácil",
    imagem: salada,
    ingredientes: [
      "40 g de salsa fresca",
      "30 g de coentro fresco",
      "20 g de hortelã fresca",
      "2 dentes de alho amassados",
      "1 limão grande (suco e raspas)",
      "2 colheres de sopa de vinagre de maçã",
      "150 ml de azeite extravirgem",
      "1 colher de chá de mel",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "Lave e seque todas as ervas. Retire as folhas.",
      "Pique finamente com faca afiada.",
      "Misture o alho, suco de limão, raspas, vinagre, mel, sal e pimenta. Bata com garfo.",
      "Adicione o azeite em fio, batendo até emulsionar.",
      "Incorpore as ervas picadas.",
      "Transfira para vidro com tampa.",
      "Conserva-se na geladeira por até 7 dias. Mexa antes de usar.",
    ],
    dicaBeatriz:
      "Sirva este vinagrete em jarrinhos de vidro à mesa para cada pessoa. Vinagrete jogado cedo murcha as folhas. Jogado à mesa, na hora, mantém tudo fresco e crocante.",
    beneficios: [
      "Vitamina C e ferro da salsa",
      "Digestivo (coentro e hortelã)",
      "Antioxidante das ervas",
    ],
  },
  {
    id: "sal-aromatizado",
    titulo: "Sal Aromatizado com Ervas das Escrituras",
    categoria: "Ervas e Temperos",
    versiculo: "Mateus 5:13",
    descricao: "Vós sois o sal da terra; e se o sal for insípido, com que se há de salgar?",
    rendimento: "200 g",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: salada,
    ingredientes: [
      "200 g de sal grosso (preferencialmente marinho)",
      "2 colheres de sopa de orégano seco",
      "2 colheres de sopa de alecrim seco",
      "1 colher de sopa de tomilho seco",
      "1 colher de sopa de manjericão seco",
      "1 colher de sopa de páprica doce",
      "1 colher de chá de pimenta-do-reino moída",
      "1 colher de chá de cominho em pó",
      "2 dentes de alho frescos amassados",
      "Raspas de 1 limão",
    ],
    preparo: [
      "Coloque o sal numa tigela grande.",
      "Acrescente todas as ervas, páprica, pimenta, cominho, alho e raspas de limão.",
      "Esfregue com as mãos por 2 minutos para liberar os óleos essenciais.",
      "Espalhe em assadeira com papel manteiga.",
      "Deixe descansar em local seco por 24 horas (ou forno desligado levemente aberto).",
      "Transfira para pote de vidro com tampa hermética.",
      "Use menos do que sal comum — este tempera muito mais.",
      "Conserva-se por até 6 meses.",
    ],
    dicaBeatriz:
      "Faça um pote para sua casa e dois para presentear. Sal aromatizado caseiro em vidrinho bonito com etiqueta escrita à mão é um dos presentes mais bonitos que existem. Custa pouco, vale ouro.",
    beneficios: [
      "Sem aditivos químicos",
      "Ervas com propriedades medicinais",
      "Reduz o uso de sal refinado",
    ],
  },

  // ── SOBREMESAS ───────────────────────────────────────────────────────
  {
    id: "figos-mel",
    titulo: "Figos com Mel e Nozes ao Forno",
    categoria: "Sobremesas",
    versiculo: "Cântico dos Cânticos 2:10-13",
    descricao:
      "Levanta-te, amiga minha, formosa minha, e vem. A figueira deu os seus figos verdes.",
    rendimento: "4 porções",
    tempo: 20,
    dificuldade: "Fácil",
    imagem: figos,
    ingredientes: [
      "8 figos maduros e firmes",
      "4 colheres de sopa de mel puro",
      "50 g de nozes em pedaços",
      "1 colher de chá de canela em pó",
      "Raspas de 1 limão",
      "1 colher de sopa de azeite extravirgem",
      "4 colheres de sopa de iogurte natural (opcional)",
    ],
    preparo: [
      "Preaqueça o forno a 200 °C.",
      "Lave os figos e corte em cruz no topo, criando uma flor aberta.",
      "Disponha em assadeira pequena com abertura para cima.",
      "Coloque mel dentro de cada figo (1 colher de chá por unidade).",
      "Distribua as nozes, polvilhe canela e raspas de limão.",
      "Regue com azeite e leve ao forno por 12 minutos.",
      "Sirva morno com iogurte natural ao lado.",
    ],
    dicaBeatriz:
      "Figos maduros são frágeis — manuseie com cuidado. E o iogurte ao lado equilibra o doce do mel. Não é decoração — é parte do prato.",
    beneficios: ["Potássio e fibra do figo", "Mel antimicrobiano", "Ômega-3 das nozes"],
  },
  {
    id: "maca-assada",
    titulo: "Maçã Assada com Canela e Mel",
    categoria: "Sobremesas",
    versiculo: "Deuteronômio 28:12",
    descricao: "O Senhor te abençoará em todas as obras das tuas mãos.",
    rendimento: "4 porções",
    tempo: 45,
    dificuldade: "Fácil",
    imagem: u("photo-1567306226416-28f0efdc88ce"),
    ingredientes: [
      "4 maçãs vermelhas médias (gala ou fuji)",
      "4 colheres de sopa de mel",
      "1 colher de sopa de canela em pó",
      "1 colher de chá de cravo em pó",
      "40 g de nozes em pedaços",
      "40 g de uvas-passas",
      "2 colheres de sopa de manteiga sem sal (ou azeite)",
      "Suco de meio limão",
      "100 ml de água",
    ],
    preparo: [
      "Preaqueça o forno a 180 °C.",
      "Retire o miolo de cada maçã, mantendo a base intacta.",
      "Misture nozes, passas, 2 colheres de mel, canela e cravo.",
      "Recheie cada maçã com a mistura.",
      "Coloque manteiga sobre cada maçã recheada.",
      "Arrume em assadeira, regue o mel restante e adicione água ao fundo.",
      "Leve ao forno por 30 a 35 minutos, regando 2 vezes.",
      "Sirva morna com o xarope da assadeira por cima.",
    ],
    dicaBeatriz:
      "O xarope que se forma no fundo da assadeira é metade do prato. Não jogue fora. Sirva cada maçã com uma colherada generosa dele por cima.",
    beneficios: [
      "Pectina da maçã (colesterol)",
      "Canela estabiliza a glicemia",
      "Ferro das passas",
    ],
  },
  {
    id: "tamara-recheada",
    titulo: "Tâmara Recheada com Pasta de Amêndoa",
    categoria: "Sobremesas",
    versiculo: "Isaías 55:2",
    descricao: "Comei o que é bom, e a vossa alma se deleite na gordura.",
    rendimento: "12 unidades",
    tempo: 20,
    dificuldade: "Fácil",
    imagem: u("photo-1562440499-64c9a111f713"),
    ingredientes: [
      "12 tâmaras grandes (preferencialmente medjool)",
      "6 colheres de sopa de pasta de amêndoa (ou pasta de amendoim sem açúcar)",
      "12 amêndoas inteiras",
      "2 colheres de sopa de coco ralado sem açúcar",
      "1 colher de chá de canela em pó",
      "1 colher de sopa de mel",
      "Pitada de flor de sal (opcional)",
    ],
    preparo: [
      "Faça um corte longitudinal em cada tâmara e retire o caroço.",
      "Misture a pasta de amêndoa, mel e canela.",
      "Recheie cada tâmara com a mistura.",
      "Coloque uma amêndoa sobre o recheio de cada tâmara.",
      "Disponha em travessa e polvilhe coco ralado.",
      "Finalize com flor de sal se desejar.",
      "Sirva em temperatura ambiente com chá de hortelã.",
    ],
    dicaBeatriz:
      "Tâmaras medjool são suculentas e macias. São mais caras, mas valem para esta receita. Se não encontrar, hidrate as comuns em água morna por 10 minutos.",
    beneficios: [
      "Energia natural sem açúcar refinado",
      "Magnésio e potássio das tâmaras",
      "Vitamina E das amêndoas",
    ],
  },
  {
    id: "iogurte-mel",
    titulo: "Sobremesa de Iogurte com Mel e Granola",
    categoria: "Sobremesas",
    versiculo: "Êxodo 3:8",
    descricao: "Uma terra que mana leite e mel.",
    rendimento: "4 porções",
    tempo: 35,
    dificuldade: "Fácil",
    imagem: u("photo-1488477181946-6428a0291777"),
    ingredientes: [
      "— Para a granola caseira (rende 400 g) —",
      "200 g de aveia em flocos grossos",
      "50 g de nozes em pedaços",
      "50 g de amêndoas em lascas",
      "30 g de sementes de girassol",
      "4 colheres de sopa de mel",
      "3 colheres de sopa de azeite",
      "1 colher de chá de canela e pitada de sal",
      "— Para servir (por porção) —",
      "200 g de iogurte natural integral",
      "2 colheres de sopa de granola caseira",
      "1 colher de chá de mel",
      "Fruta fresca da estação",
    ],
    preparo: [
      "Preaqueça o forno a 160 °C.",
      "Misture aveia, nozes, amêndoas, sementes, canela e sal.",
      "Misture mel e azeite morno. Despeje sobre a aveia e mexa bem.",
      "Espalhe em assadeira com papel manteiga em camada fina.",
      "Asse por 25 a 30 minutos, mexendo a cada 8 minutos.",
      "Deixe esfriar completamente na assadeira (fica crocante ao esfriar).",
      "Para servir: camadas de iogurte, granola, mel e fruta num copo bonito.",
    ],
    dicaBeatriz:
      "Faça a granola no domingo de manhã. Uma assadeira basta para a semana inteira. E lembre-se: ela dobra de crocância depois de esfriar. Deixe quieta antes de provar.",
    beneficios: [
      "Probiótico do iogurte",
      "Beta-glucana da aveia para colesterol",
      "Mel enzimas digestivas",
    ],
  },
  {
    id: "creme-tamaras",
    titulo: "Creme de Tâmaras — Sem Açúcar, Sem Leite",
    categoria: "Sobremesas",
    versiculo: "Provérbios 5:19",
    descricao: "A doçura há de habitar no seu coração.",
    rendimento: "4 porções",
    tempo: 15,
    dificuldade: "Fácil",
    imagem: figos,
    ingredientes: [
      "300 g de tâmaras sem caroço (medjool ou hidratadas)",
      "200 ml de água quente",
      "100 g de castanha-de-caju crua (molho de 2 h)",
      "1 colher de sopa de cacau em pó 100% (opcional)",
      "1 colher de chá de extrato de baunilha",
      "Pitada de sal",
      "Coco ralado e frutas vermelhas para finalizar",
    ],
    preparo: [
      "Coloque as tâmaras de molho em água quente por 10 minutos. Escorra, reservando 100 ml da água.",
      "Escorra também as castanhas-de-caju.",
      "Bata no liquidificador as tâmaras, castanhas, água reservada, cacau, baunilha e sal.",
      "Bata em velocidade alta por 3 a 5 minutos até obter creme absolutamente liso.",
      "Transfira para 4 ramequins. Cubra com filme em contato com a superfície.",
      "Leve à geladeira por pelo menos 4 horas.",
      "Na hora de servir, finalize com coco ralado e frutas vermelhas.",
    ],
    dicaBeatriz:
      "A castanha de molho é o que dá a textura sedosa. Castanha seca fica granulosa. E na geladeira por uma noite inteira, o sabor fica ainda mais profundo.",
    beneficios: [
      "Adoçado apenas por tâmaras naturais",
      "Cálcio e magnésio da castanha",
      "Fibras solúveis",
    ],
  },
  {
    id: "pera-vinho",
    titulo: "Pera ao Vinho Suave com Cravo e Canela",
    categoria: "Sobremesas",
    versiculo: "Oseias 9:10",
    descricao: "Como a figueira que dá os seus primeiros figos.",
    rendimento: "4 porções",
    tempo: 50,
    dificuldade: "Médio",
    imagem: u("photo-1458014854819-1a40aa70211c"),
    ingredientes: [
      "4 peras firmes com cabo (williams ou portuguesa)",
      "700 ml de suco de uva integral (sem açúcar) OU 500 ml de vinho tinto seco + 200 ml de água",
      "3 colheres de sopa de mel",
      "2 paus de canela",
      "4 cravos-da-índia",
      "1 anis-estrelado (opcional)",
      "Raspas de 1 laranja e suco de meio limão",
    ],
    preparo: [
      "Descasque as peras mantendo o cabo. Corte fininha a base para ficarem em pé.",
      "Numa panela alta, misture o suco, mel, canela, cravo, anis, raspas de laranja e limão.",
      "Aqueça até ferver. Reduza para fogo baixo.",
      "Coloque as peras em pé e cozinhe tampado por 25 a 35 minutos, virando a cada 10.",
      "Retire as peras. Ferva o caldo mais 10 a 15 minutos até formar calda brilhante.",
      "Sirva cada pera com a calda generosa por cima.",
    ],
    dicaBeatriz:
      "Esta sobremesa fica ainda mais bonita em pratos brancos, para a cor avinhada se destacar. Quanto mais tempo as peras ficam viradas, mais uniformes ficam.",
    beneficios: [
      "Polifenóis da uva antioxidantes",
      "Canela estabiliza glicemia",
      "Fibra da pera para digestão",
    ],
  },
  {
    id: "bolo-mel",
    titulo: "Bolo de Mel e Nozes Sem Açúcar",
    categoria: "Sobremesas",
    versiculo: "Salmos 23:5",
    descricao: "E será suave a tua doçura.",
    rendimento: "10 fatias",
    tempo: 60,
    dificuldade: "Médio",
    imagem: u("photo-1559620192-032c4bc4674e"),
    ingredientes: [
      "300 g de farinha de trigo integral",
      "200 ml de mel puro",
      "3 ovos",
      "100 ml de azeite (ou óleo neutro)",
      "100 ml de leite",
      "100 g de nozes picadas",
      "1 colher de sopa de canela em pó",
      "1 colher de chá de cravo em pó",
      "1 colher de chá de bicarbonato de sódio",
      "1 colher de chá de fermento em pó",
      "Pitada de sal e raspas de 1 laranja",
    ],
    preparo: [
      "Preaqueça o forno a 170 °C. Unte uma forma de bolo inglês.",
      "Bata o mel, ovos e azeite até mistura homogênea.",
      "Acrescente o leite e as raspas de laranja.",
      "Misture separadamente a farinha, canela, cravo, bicarbonato, fermento e sal.",
      "Una os secos aos líquidos, mexendo até incorporar (não bata em excesso).",
      "Acrescente as nozes com espátula.",
      "Despeje na forma e asse por 40 a 45 minutos.",
      "Deixe esfriar 15 minutos antes de desenformar.",
    ],
    dicaBeatriz:
      "Este bolo fica melhor no segundo dia. O mel se assenta, a canela se intensifica. Faça à noite, deixe descansar, sirva no café da manhã seguinte.",
    beneficios: [
      "Mel rico em enzimas e antioxidantes",
      "Nozes ômega-3 e vitamina E",
      "Farinha integral fibras",
    ],
  },
  {
    id: "roma-iogurte",
    titulo: "Romã com Iogurte e Hortelã",
    categoria: "Sobremesas",
    versiculo: "Cântico dos Cânticos 7:12",
    descricao: "Lá te darei o meu amor, onde já tinham desabrochado as romeiras.",
    rendimento: "4 porções",
    tempo: 5,
    dificuldade: "Fácil",
    imagem: u("photo-1464965911861-746a04b4bca6"),
    ingredientes: [
      "400 g de iogurte natural integral (sem açúcar)",
      "1 romã grande (sementes)",
      "4 colheres de chá de mel",
      "1 colher de sopa de hortelã fresca picada",
      "4 colheres de chá de pistache sem sal (opcional)",
    ],
    preparo: [
      "Corte a romã ao meio e retire as sementes batendo as costas com colher de pau.",
      "Divida o iogurte entre 4 taças individuais.",
      "Distribua as sementes de romã sobre cada porção.",
      "Regue com mel e polvilhe hortelã.",
      "Finalize com pistache se for usar.",
      "Sirva imediatamente, gelado.",
    ],
    dicaBeatriz:
      "Esta sobremesa pede iogurte de boa qualidade. Iogurte aguado estraga o prato. Procure o mais cremoso possível — é o ingrediente principal disfarçado de coadjuvante.",
    beneficios: [
      "Polifenóis da romã anticâncer",
      "Probiótico do iogurte",
      "Pistache rico em proteína",
    ],
  },

  // ── RECEITAS ÂNCORA ──────────────────────────────────────────────────
  {
    id: "pao-discipulos",
    titulo: "Pão dos Discípulos — Fermentação Natural",
    categoria: "Receitas Âncora",
    versiculo: "Lucas 9:16",
    descricao:
      "E, tomando os cinco pães e os dois peixes, e olhando para o céu, os abençoou, e partiu-os.",
    rendimento: "1 pão grande (10 fatias)",
    tempo: 90,
    dificuldade: "Avançado",
    imagem: pao,
    ingredientes: [
      "100 g de fermento natural ativo (alimentado nas últimas 4 a 8 h)",
      "350 ml de água filtrada morna (30 °C)",
      "400 g de farinha de trigo branca",
      "100 g de farinha de trigo integral",
      "10 g de sal fino",
    ],
    preparo: [
      "Misture o fermento natural com a água morna. Mexa para dissolver.",
      "Acrescente as farinhas. Misture com colher de pau até massa rústica. Descanse 30 minutos (autólise).",
      "Adicione o sal e sove por 5 minutos, esticando e dobrando dentro da tigela.",
      "Nos primeiros 2 h de fermentação, a cada 30 min faça uma dobra (estique um lado e dobre sobre a massa). Repita por 2 h.",
      "Fermente em temperatura ambiente por 4 a 6 h até dobrar de volume.",
      "Modele em bola e leve à geladeira por 12 a 18 h em tigela forrada com pano enfarinhado.",
      "Preaqueça o forno a 230 °C com panela de ferro tampada dentro por 30 min.",
      "Vire a massa na panela. Corte o topo com lâmina. Asse tampado 25 min, depois destampado 15 a 20 min.",
      "Deixe esfriar 1 h antes de cortar.",
    ],
    dicaBeatriz:
      "Eu sei que parece muito trabalho. Mas o que você está fazendo não é apenas um pão — é o gesto mais ancestral da humanidade. Faça uma vez, partilhe com oração antes, e vai entender por que vale cada minuto.",
    beneficios: [
      "Fermentação natural prébiótica",
      "Reduz o índice glicêmico do pão",
      "Sem aditivos industriais",
    ],
  },
  {
    id: "pao-azimo",
    titulo: "Pão Ázimo — Pão Sem Fermento da Páscoa",
    categoria: "Receitas Âncora",
    versiculo: "Êxodo 12:39",
    descricao:
      "E eles cozeram a massa que levaram do Egito, fazendo dela bolos asmos, porque não tinha levedado.",
    rendimento: "6 pães",
    tempo: 30,
    dificuldade: "Fácil",
    imagem: pao,
    ingredientes: [
      "300 g de farinha de trigo integral",
      "150 ml de água morna",
      "3 colheres de sopa de azeite extravirgem",
      "1 colher de chá de sal",
    ],
    preparo: [
      "Preaqueça o forno a 220 °C com uma assadeira vazia dentro.",
      "Misture a farinha e o sal. Adicione água morna e azeite.",
      "Misture e sove por 5 minutos até massa lisa. Descanse 10 min.",
      "Divida em 6 porções e abra com rolo até discos finos de 20 cm.",
      "Fure cada disco várias vezes com garfo.",
      "Coloque na assadeira quente e asse 3 a 5 minutos de cada lado.",
      "Sirva quente com homus, babaganuche ou azeite e sal.",
    ],
    dicaBeatriz:
      "Faça este pão no dia da Páscoa com sua família. Antes de servir, abra a Bíblia em Êxodo 12 e leia o trecho. Não é apenas uma refeição — é uma transmissão de fé.",
    beneficios: [
      "Sem fermento (digestão mais leve)",
      "Farinha integral fibras",
      "Azeite anti-inflamatório",
    ],
  },
  {
    id: "cordeiro-pascal",
    titulo: "Cordeiro Pascal Assado com Ervas Amargas",
    categoria: "Receitas Âncora",
    versiculo: "Êxodo 12:8",
    descricao:
      "E naquela noite comerão a carne assada no fogo, com pães ázimos; com ervas amargosas a comerão.",
    rendimento: "6–8 porções",
    tempo: 180,
    dificuldade: "Avançado",
    imagem: u("photo-1603360946369-dc9bb6258143"),
    ingredientes: [
      "1,5 kg de paleta ou pernil de cordeiro",
      "6 dentes de alho amassados",
      "3 ramos de alecrim fresco",
      "3 ramos de tomilho fresco",
      "1 maço de hortelã fresca",
      "100 ml de azeite extravirgem",
      "2 limões (suco e raspas)",
      "1 colher de sopa de sal grosso e pimenta moída",
      "1 colher de sopa de cominho em pó",
      "200 ml de água ou caldo de carne",
      "Rúcula ou agrião fresco para servir (ervas amargas)",
    ],
    preparo: [
      "Retire o cordeiro da geladeira 1 h antes de cozinhar.",
      "Preaqueça o forno a 160 °C.",
      "Amasse alho, sal, pimenta, cominho, suco e raspas de limão. Adicione metade do azeite — pasta pronta.",
      "Esfregue a pasta por todo o cordeiro, sob as dobras.",
      "Espalhe alecrim, tomilho e hortelã na assadeira. Coloque o cordeiro por cima.",
      "Regue com o azeite restante e adicione a água no fundo.",
      "Cubra com papel-alumínio bem vedado. Asse por 2 h e 30 min.",
      "Retire o alumínio. Aumente para 200 °C e asse mais 25 min.",
      "Deixe descansar 15 min. Sirva com rúcula ao lado.",
    ],
    dicaBeatriz:
      "As ervas amargas ao lado não são decoração — representam a amargura do cativeiro no Egito. Quando você serve cordeiro com rúcula crua, repete um gesto de mais de três mil anos. Conte essa história à mesa.",
    beneficios: [
      "Proteína completa de alta qualidade",
      "Ferro heme de alta absorção",
      "Zinco para imunidade",
    ],
  },
  {
    id: "suco-sagrado",
    titulo: "Suco Sagrado da Manhã — Laranja, Gengibre e Hortelã",
    categoria: "Receitas Âncora",
    versiculo: "Cântico dos Cânticos 4:11",
    descricao: "Os teus lábios são como o favo que goteja.",
    rendimento: "1 porção",
    tempo: 5,
    dificuldade: "Fácil",
    imagem: suco,
    ingredientes: [
      "2 laranjas maduras (suco fresco — 200 ml)",
      "1 pedaço de gengibre fresco — aproximadamente 2 cm",
      "8 a 10 folhas de hortelã fresca",
      "100 ml de água gelada",
      "1 colher de chá de mel (opcional)",
      "Pedras de gelo a gosto",
    ],
    preparo: [
      "Esprema as laranjas e reserve o suco.",
      "Descasque o gengibre e corte em fatias finas.",
      "Lave as folhas de hortelã.",
      "No liquidificador, coloque o suco de laranja, gengibre, hortelã e água gelada.",
      "Bata por 30 segundos a 1 minuto.",
      "Coe numa peneira fina (opcional — pode beber sem coar).",
      "Acrescente mel se quiser e sirva com gelo e hortelã.",
      "Beba devagar, em jejum, antes do café da manhã.",
    ],
    dicaBeatriz:
      "Faça este suco todos os dias nos primeiros 21 dias. Em 1 semana, o inchaço do rosto começa a diminuir. Em 2, a barriga fica mais leve. Em 3, uma energia que você não tinha há anos. É o gesto mais simples que você pode fazer agora pelo templo do seu corpo.",
    beneficios: [
      "Vitamina C (2× necessidade diária)",
      "Gengibre anti-inflamatório e termogênico",
      "Hortelã digestiva e detox",
    ],
  },
  {
    id: "vinho-uvas",
    titulo: "Vinho Suave de Uvas — Bebida Fermentada Sem Álcool",
    categoria: "Receitas Âncora",
    versiculo: "Mateus 26:27",
    descricao: "Tomando o cálice, e dando graças, deu-lho, dizendo: Bebei dele todos.",
    rendimento: "1 litro (6–8 porções)",
    tempo: 30,
    dificuldade: "Fácil",
    imagem: suco,
    ingredientes: [
      "1 litro de suco de uva integral 100% (sem açúcar)",
      "4 cravos-da-índia",
      "1 pau de canela",
      "4 grãos de cardamomo levemente abertos (opcional)",
      "Raspas de meia laranja e meio limão",
      "2 colheres de sopa de mel (opcional)",
      "1 colher de sopa de uvas-passas escuras",
    ],
    preparo: [
      "Aqueça o suco em fogo baixo sem ferver por 5 minutos.",
      "Adicione cravo, canela, cardamomo, raspas de laranja e limão.",
      "Desligue e deixe em infusão por 30 minutos.",
      "Coe com peneira fina. Acrescente mel e dissolva.",
      "Transfira para garrafa de vidro esterilizada.",
      "Adicione as passas (starter de fermentação).",
      "Tampe sem apertar muito e deixe em local fresco por 24 a 36 horas.",
      "Retire as passas, leve à geladeira por 4 a 6 h e sirva gelado em taças.",
    ],
    dicaBeatriz:
      "Esta bebida não tem álcool — mas tem a alma do vinho: o ritual de servir em taças, o gesto de erguer o cálice, a profundidade das especiarias. Use em ceias de família, batismos, Páscoa. Toda a família pode partilhar.",
    beneficios: [
      "Resveratrol das uvas antioxidante",
      "Canela e cravo anti-inflamatórios",
      "Zero álcool",
    ],
  },
];

export const categorias: Categoria[] = [
  "Pratos Principais",
  "Saladas e Acompanhamentos",
  "Sopas",
  "Ervas e Temperos",
  "Sobremesas",
  "Receitas Âncora",
];

export const categoriaES: Record<Categoria, string> = {
  "Pratos Principais": "Platos Principales",
  "Saladas e Acompanhamentos": "Ensaladas y Acompañamientos",
  Sopas: "Sopas",
  "Ervas e Temperos": "Hierbas y Condimentos",
  Sobremesas: "Postres",
  "Receitas Âncora": "Recetas Ancla",
};

export const dificuldadeES: Record<string, string> = {
  Fácil: "Fácil",
  Médio: "Medio",
  Avançado: "Avanzado",
};

const BOOK_PT_TO_ES: Record<string, string> = {
  Gênesis: "Génesis",
  Êxodo: "Éxodo",
  Levítico: "Levítico",
  Números: "Números",
  Deuteronômio: "Deuteronomio",
  Josué: "Josué",
  Juízes: "Jueces",
  Rute: "Rut",
  "1 Samuel": "1 Samuel",
  "2 Samuel": "2 Samuel",
  "1 Reis": "1 Reyes",
  "2 Reis": "2 Reyes",
  "1 Crônicas": "1 Crónicas",
  "2 Crônicas": "2 Crónicas",
  Esdras: "Esdras",
  Neemias: "Nehemías",
  Ester: "Ester",
  Jó: "Job",
  Salmos: "Salmos",
  Provérbios: "Proverbios",
  Eclesiastes: "Eclesiastés",
  "Cântico dos Cânticos": "Cantares",
  Isaías: "Isaías",
  Jeremias: "Jeremías",
  Lamentações: "Lamentaciones",
  Ezequiel: "Ezequiel",
  Daniel: "Daniel",
  Oseias: "Oseas",
  Joel: "Joel",
  Amós: "Amós",
  Miqueias: "Miqueas",
  Naum: "Nahúm",
  Habacuque: "Habacuc",
  Sofonias: "Sofonías",
  Ageu: "Hageo",
  Zacarias: "Zacarías",
  Malaquias: "Malaquías",
  Mateus: "Mateo",
  Marcos: "Marcos",
  Lucas: "Lucas",
  João: "Juan",
  Atos: "Hechos",
  Romanos: "Romanos",
  "1 Coríntios": "1 Corintios",
  "2 Coríntios": "2 Corintios",
  Gálatas: "Gálatas",
  Efésios: "Efesios",
  Filipenses: "Filipenses",
  Colossenses: "Colosenses",
  "1 Tessalonicenses": "1 Tesalonicenses",
  "2 Tessalonicenses": "2 Tesalonicenses",
  "1 Timóteo": "1 Timoteo",
  "2 Timóteo": "2 Timoteo",
  Tito: "Tito",
  Filemom: "Filemón",
  Hebreus: "Hebreos",
  Tiago: "Santiago",
  "1 Pedro": "1 Pedro",
  "2 Pedro": "2 Pedro",
  "1 João": "1 Juan",
  "2 João": "2 Juan",
  "3 João": "3 Juan",
  Judas: "Judas",
  Apocalipse: "Apocalipsis",
};

export function translateVersiculo(ref: string, lang: Lang): string {
  if (lang !== "es") return ref;
  // Sort by length desc so "Cântico dos Cânticos" matches before "Cântico"
  const entries = Object.entries(BOOK_PT_TO_ES).sort((a, b) => b[0].length - a[0].length);
  for (const [pt, es] of entries) {
    if (ref.startsWith(pt)) return es + ref.slice(pt.length);
  }
  return ref;
}

/** Returns the recipe merged with its Spanish translation and admin overrides */
export function getRecipeLang(id: string, lang: Lang): Receita | undefined {
  const base = recipes.find((r) => r.id === id);
  if (!base) return undefined;

  const overrides = loadOverrides();
  const ov = overrides.recipes[id] ?? {};

  // Start with base recipe
  let result: Receita = { ...base };

  // Apply image: IndexedDB first, then legacy localStorage fallback
  const idbImg = getCachedImages()[id];
  if (idbImg) result = { ...result, imagem: idbImg };
  else if (ov.imagem && ov.imagem.trim() !== "") result = { ...result, imagem: ov.imagem };

  if (lang === "es") {
    const tr = recipeTranslationsES[id];
    if (tr) {
      result = {
        ...result,
        titulo: tr.titulo,
        descricao: tr.descricao,
        rendimento: tr.rendimento,
        ingredientes: tr.ingredientes,
        preparo: tr.preparo,
        dicaBeatriz: tr.dicaBeatriz,
        beneficios: tr.beneficios,
      };
    }
    // Admin ES title override takes priority
    if (ov.titulo_es && ov.titulo_es.trim() !== "") result = { ...result, titulo: ov.titulo_es };
    // Translate Bible reference
    result = { ...result, versiculo: translateVersiculo(result.versiculo, "es") };
  } else {
    // Admin PT title override
    if (ov.titulo && ov.titulo.trim() !== "") result = { ...result, titulo: ov.titulo };
  }

  return result;
}

/** Returns all recipes with translations and admin overrides applied */
export function getRecipesLang(lang: Lang): Receita[] {
  const overrides = loadOverrides();
  return recipes.map((r) => {
    const ov = overrides.recipes[r.id] ?? {};
    let result = { ...r };

    // Apply image: IndexedDB first, then legacy localStorage fallback
    const idbImg = getCachedImages()[r.id];
    if (idbImg) result = { ...result, imagem: idbImg };
    else if (ov.imagem && ov.imagem.trim() !== "") result = { ...result, imagem: ov.imagem };

    if (lang === "es") {
      const tr = recipeTranslationsES[r.id];
      if (tr) result = { ...result, titulo: tr.titulo };
      if (ov.titulo_es && ov.titulo_es.trim() !== "") result = { ...result, titulo: ov.titulo_es };
    } else {
      if (ov.titulo && ov.titulo.trim() !== "") result = { ...result, titulo: ov.titulo };
    }

    return result;
  });
}

export const getRecipe = (id: string) => recipes.find((r) => r.id === id);
