/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucoSagradoRouteImport } from './routes/suco-sagrado'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ProtocoloRouteImport } from './routes/protocolo'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MesaUnicaRouteImport } from './routes/mesa-unica'
import { Route as FundamentosRouteImport } from './routes/fundamentos'
import { Route as DevocionalRouteImport } from './routes/devocional'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceitasIndexRouteImport } from './routes/receitas.index'
import { Route as ReceitasIdRouteImport } from './routes/receitas.$id'

const SucoSagradoRoute = SucoSagradoRouteImport.update({
  id: '/suco-sagrado',
  path: '/suco-sagrado',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloRoute = ProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaUnicaRoute = MesaUnicaRouteImport.update({
  id: '/mesa-unica',
  path: '/mesa-unica',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentosRoute = FundamentosRouteImport.update({
  id: '/fundamentos',
  path: '/fundamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionalRoute = DevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasIndexRoute = ReceitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceitasRoute,
} as any)
const ReceitasIdRoute = ReceitasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceitasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/devocional': typeof DevocionalRoute
  '/fundamentos': typeof FundamentosRoute
  '/mesa-unica': typeof MesaUnicaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/progresso': typeof ProgressoRoute
  '/protocolo': typeof ProtocoloRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/suco-sagrado': typeof SucoSagradoRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas/': typeof ReceitasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/devocional': typeof DevocionalRoute
  '/fundamentos': typeof FundamentosRoute
  '/mesa-unica': typeof MesaUnicaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/progresso': typeof ProgressoRoute
  '/protocolo': typeof ProtocoloRoute
  '/suco-sagrado': typeof SucoSagradoRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas': typeof ReceitasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/devocional': typeof DevocionalRoute
  '/fundamentos': typeof FundamentosRoute
  '/mesa-unica': typeof MesaUnicaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/progresso': typeof ProgressoRoute
  '/protocolo': typeof ProtocoloRoute
  '/receitas': typeof ReceitasRouteWithChildren
  '/suco-sagrado': typeof SucoSagradoRoute
  '/receitas/$id': typeof ReceitasIdRoute
  '/receitas/': typeof ReceitasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/devocional'
    | '/fundamentos'
    | '/mesa-unica'
    | '/onboarding'
    | '/perfil'
    | '/progresso'
    | '/protocolo'
    | '/receitas'
    | '/suco-sagrado'
    | '/receitas/$id'
    | '/receitas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/devocional'
    | '/fundamentos'
    | '/mesa-unica'
    | '/onboarding'
    | '/perfil'
    | '/progresso'
    | '/protocolo'
    | '/suco-sagrado'
    | '/receitas/$id'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/devocional'
    | '/fundamentos'
    | '/mesa-unica'
    | '/onboarding'
    | '/perfil'
    | '/progresso'
    | '/protocolo'
    | '/receitas'
    | '/suco-sagrado'
    | '/receitas/$id'
    | '/receitas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DevocionalRoute: typeof DevocionalRoute
  FundamentosRoute: typeof FundamentosRoute
  MesaUnicaRoute: typeof MesaUnicaRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ProgressoRoute: typeof ProgressoRoute
  ProtocoloRoute: typeof ProtocoloRoute
  ReceitasRoute: typeof ReceitasRouteWithChildren
  SucoSagradoRoute: typeof SucoSagradoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suco-sagrado': {
      id: '/suco-sagrado'
      path: '/suco-sagrado'
      fullPath: '/suco-sagrado'
      preLoaderRoute: typeof SucoSagradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo': {
      id: '/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof ProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa-unica': {
      id: '/mesa-unica'
      path: '/mesa-unica'
      fullPath: '/mesa-unica'
      preLoaderRoute: typeof MesaUnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentos': {
      id: '/fundamentos'
      path: '/fundamentos'
      fullPath: '/fundamentos'
      preLoaderRoute: typeof FundamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocional': {
      id: '/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof DevocionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas/': {
      id: '/receitas/'
      path: '/'
      fullPath: '/receitas/'
      preLoaderRoute: typeof ReceitasIndexRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/receitas/$id': {
      id: '/receitas/$id'
      path: '/$id'
      fullPath: '/receitas/$id'
      preLoaderRoute: typeof ReceitasIdRouteImport
      parentRoute: typeof ReceitasRoute
    }
  }
}

interface ReceitasRouteChildren {
  ReceitasIdRoute: typeof ReceitasIdRoute
  ReceitasIndexRoute: typeof ReceitasIndexRoute
}

const ReceitasRouteChildren: ReceitasRouteChildren = {
  ReceitasIdRoute: ReceitasIdRoute,
  ReceitasIndexRoute: ReceitasIndexRoute,
}

const ReceitasRouteWithChildren = ReceitasRoute._addFileChildren(
  ReceitasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DevocionalRoute: DevocionalRoute,
  FundamentosRoute: FundamentosRoute,
  MesaUnicaRoute: MesaUnicaRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ProgressoRoute: ProgressoRoute,
  ProtocoloRoute: ProtocoloRoute,
  ReceitasRoute: ReceitasRouteWithChildren,
  SucoSagradoRoute: SucoSagradoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
